### ISSUE TITLE
knative.dev/pkg/metrics/metrics.go:38:12: undefined: tag.MustNewKey

### ISSUE THREAD

**Issue by Uvindu96** [knative/pkg#1020]
## Expected Behavior
I'm trying to build a Knative service spec using go lang, I have used the import "knative.dev/serving/pkg/apis/serving/v1" to import Knative modules to my project. This should allow me to create a Knative service spec.
my kantive version is (0.12)

## Actual Behavior
 when building my project using the operator-sdk(version 0.15) it gives me the following error.

## Steps to Reproduce the Problem

1. import the knative modules (import "knative.dev/serving/pkg/apis/serving/v1") to the project
2. go mod init
3. go mod vendor
4. operator-sdk build <image-name>:v0.6.9

## Additional Info
I got the following error
# knative.dev/pkg/metrics
vendor/knative.dev/pkg/metrics/metrics.go:38:12: undefined: tag.MustNewKey
vendor/knative.dev/pkg/metrics/metrics.go:41:12: undefined: tag.MustNewKey
vendor/knative.dev/pkg/metrics/metrics.go:43:12: undefined: tag.MustNewKey
vendor/knative.dev/pkg/metrics/metrics.go:45:14: undefined: tag.MustNewKey
vendor/knative.dev/pkg/metrics/metrics.go:47:12: undefined: tag.MustNewKey
vendor/knative.dev/pkg/metrics/metrics.go:49:12: undefined: tag.MustNewKey
vendor/knative.dev/pkg/metrics/metrics.go:97:4: undefined: workqueue.HistogramMetric
vendor/knative.dev/pkg/metrics/metrics.go:166:4: undefined: workqueue.HistogramMetric
vendor/knative.dev/pkg/metrics/workqueue.go:69:60: undefined: workqueue.HistogramMetric
vendor/knative.dev/pkg/metrics/workqueue.go:121:65: undefined: workqueue.HistogramMetric
vendor/knative.dev/pkg/metrics/metrics.go:166:4: too many errors
Error: failed to build operator binary: failed to exec []string{"go", "build", "-o", "/home/uvindu/GO/Project1/src/github.com/wso2/k8s-apim-operator/apim-operator/build/_output/bin/apim-operator", "-gcflags", "all=-trimpath=/home/uvindu/GO/Project1/src/github.com/wso2/k8s-apim-operator", "-asmflags", "all=-trimpath=/home/uvindu/GO/Project1/src/github.com/wso2/k8s-apim-operator", "-mod=vendor", "github.com/wso2/k8s-apim-operator/apim-operator/cmd/manager"}: exit status 2
Usage:
  operator-sdk build <image> [flags]

**Comment by skaslev** [comment]
`MustNewKey` is defined in the `go.opencensus.io/tag` package which seems to be missing from your project.

Knative is not using go modules yet which might explain why what you have above doesn't work.

**Comment by Uvindu96** [comment]
Thank you, I think this resolved my issue.
