### ISSUE TITLE
webhook controller has a lot of messages error messages about missing cacert

### ISSUE THREAD

**Issue by chmouel** [knative/pkg#1047]
a lot of error messages due of missing cacert have started to appears in  the `tektoncd-webhook` pod logs, this has been happenning since we did a bump to use knative.pkg-0.12  in here https://github.com/tektoncd/pipeline/pull/1894 :

```
{"level":"info","logger":"webhook","caller":"controller/controller.go:363","msg":"Reconcile failed. Time taken: 115.268µs.","knative.dev/traceid":"5c365bc2-40a6-4e9c-9af6-d6c96d690317","knative.dev/key":"webhook.pipeline.tekton.dev"}
{"level":"error","logger":"webhook","caller":"controller/controller.go:376","msg":"Reconcile error","error":"secret \"webhook-certs\" is missing \"ca-cert.pem\" key","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\t/workspace/tektoncd-pipeline-git/vendor/knative.dev/pkg/controller/controller.go:376\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/workspace/tektoncd-pipeline-git/vendor/knative.dev/pkg/controller/controller.go:362\nknative.dev/pkg/controller.(*Impl).Run.func2\n\t/workspace/tektoncd-pipeline-git/vendor/knative.dev/pkg/controller/controller.go:310"
```

They seem harmless and only shows up at boot time and for the `webhook` controller but there is quite a few of them (55) and they may look quite worrisome for the uneducated user.

/kind bug

**Comment by chmouel** [comment]
oh `prow` parses the comments 🤦‍♂

**Comment by sarathkumarpgm** [comment]
/reopen

Hi i'm getting the same issue in while installing sigstore dev, pods are not getting up due to this issue,  

{
    "level": "error",
    "ts": "2025-03-13T12:02:27.949+0530",
    "logger": "policy-controller.resource-conversion",
    "caller": "controller/controller.go:566",
    "msg": "Reconcile error",
    "commit": "4a12093-dirty",
    "knative.dev/traceid": "0e4251e2-61ae-449c-9095-a03c7a2bf881",
    "knative.dev/key": "clusterimagepolicies.policy.sigstore.dev",
    "duration": 0.000011843,
    "error": "secret \"webhook-certs\" is missing \"ca-cert.pem\" key",
    "stacktrace": "knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20230612155445-74c4be5e935e/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20230612155445-74c4be5e935e/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20230612155445-74c4be5e935e/controller/controller.go:491"
}
