### ISSUE TITLE
Adopt health checks in sharedmain

### ISSUE THREAD

**Issue by pmorie** [knative/pkg#1048]
Currently, we do not use health checks in our controllers descended from `sharedmain`. Adopting health checks will allow us to begin reporting controllers as unhealthy so that they are restarted by the kubelet. For example, we will be able to use the leaderelection health checker to begin reporting unhealthy after the leader election timeout elapsed when renewing the leader election lease.

/kind feature

## Expected Behavior

Controllers can report themselves as unhealthy so that they can be restarted.

## Actual Behavior

That doesn't happen.

**Comment by mattmoor** [comment]
We should use the shared `drainer` logic, but probably have something that does this over HTTP (no need for TLS)

**Comment by mpetason** [comment]
/assign 

I'll take a shot at this.

**Comment by mpetason** [comment]
Unassigned so someone can resolve this faster than I can.
