### ISSUE TITLE
apis.Convertible has confusing function names

### ISSUE THREAD

**Issue by dprotaso** [knative/pkg#1057]
What `ConvertUp` & `ConvertDown` should do isn't immediately obvious. 

https://github.com/knative/pkg/blob/79f10450c2609c682a2dae3762adb867c504f15b/apis/interfaces.go#L37-L45

Suggested Alternative
- `ConvertTo` & `ConvertFrom`

**Comment by dprotaso** [comment]
cc @mattmoor @vaikas @n3wscott @vagababov

**Comment by mattmoor** [comment]
I think my original suggestion was `UpFrom` and `DownTo`.  I agree that including a qualifier to indicate the asymmetry would be useful.

https://github.com/mattmoor/serving/commit/a1a18f7a190cd1bd7366779917ab300fb180da88#diff-f9e008c1b737ef87f37530e188421665R136

**Comment by n3wscott** [comment]
+1 on `xFrom` and `xTo`

I like `ConvertTo` & `ConvertFrom` because it reads to me as it is doing a conversion. I understand this, I understand `UpFrom` less

**Comment by vaikas** [comment]
+1 was super confusing and had to go digging and read with care :) make it so.

**Comment by n3wscott** [comment]
`ConvertUpTo` and `ConvertDownTo`

**Comment by dprotaso** [comment]
Are we ok with a breaking change?

**Comment by vagababov** [comment]
I can go with `ConvertUp/DownTo`.
We can do two step wherein we have both names for 2 releases.

**Comment by dgerd** [comment]
+1 on `ConvertTo` and `ConvertFrom`. I am not sure it is worth a change if we are just adding `To` to the end of the existing functions.

I am okay with a breaking change here, but we should have the fixed dependencies ready with [WIP] PRs before checking this into pkg to limit time of breakage.
