### ISSUE TITLE
[Discussion] Let’s talk about finalizers.

### ISSUE THREAD

**Issue by n3wscott** [knative/pkg#1065]
There are (at least) two camps:

1. if your controller will use a finalizes, then slap it on the resource first thing for the entire life of that resource regardless of reconciliation requirements

2. when your controller does an action that requires intervention to undo (cluster external or whatever), it then adds a finalizer to that resource.

`1.` is way easier to implement

`2.` is (in my humble opinion) is more correct because resources can clean up faster if no finalizer is really required for that resource in question

So this comes in question when I am supporting finalizers in genreconciler

which would folks want?

**Comment by grantr** [comment]
I think I prefer 1. The case you mention where 2 is better is deleting an object that doesn't need to finalize right? In that case deleting the finalizer is very fast. Doesn't seem worth a more complicated api.
But if you can make 2 work with a simple api, go for it :)

**Comment by antoineco** [comment]
I agree that finalizers should be there for a reason, so leaning towards **2.**.
Like Grant, I'm unconvinced about the speed argument, so I wouldn't sacrifice on simplicity for that only reason.

**Comment by lionelvillard** [comment]
@antoineco Do you mean leaning toward `1`? `1` is the simple, safe case.

**Comment by antoineco** [comment]
@lionelvillard No, I really meant **2**, which sounds more correct to me. By "there for a reason" I meant that I'm not expecting a finalizer to exist on an object unless its controller has a good reason to put it there (which is rarely the case).

On the other hand, I understand that **1** is the simpler option, so I don't mind if @n3wscott finds out after some tinkering that the implementation of _2_ is too complex and falls back to _1_.

**Comment by lionelvillard** [comment]
I usually lean towards safety and simplicity, especially for controllers. +1 for `1`.

**Comment by n3wscott** [comment]
I am going to take a look at implementing this today, it is required for a lot of eventing components. To be clear, I would not opt in all things to use finalizers for 1, the diff is the controller could opt in and then if it does, it would get a finalizer or not. Let me dig in and see where I end up.

**Comment by n3wscott** [comment]
Went with 1.
