### ISSUE TITLE
Generate OpenAPI for CRDs in Knative.

### ISSUE THREAD

**Issue by n3wscott** [knative/pkg#1130]
From Eventing WG notes:

[n3wscott] Dropped handwritten OpenAPI in CRDs (some), 0.14 will bring it back with automation. Looking for someone who wants to work on this (with me?).
Still have validating webhooks, so no behavior change
Hard to maintain without generation (like controller-tools)
 - [aslom] If schema isn't there, users won't know how to create objects without reading the docs
 - [lionel] Will we keep both openapi validation and webhook validation?
 - [vaikas] webhook validation can do more complex things than openapi
Needed to drop OpenAPI because CRD in new version of k8s started dropping unknown fields
Kubernetes only supports a subset of OpenAPI, not jsonSchema
 - [aslom] OpenAPI schemas allows testing alignment of channel schemas with shared schemas

**Comment by dprotaso** [comment]
Related: https://github.com/knative/serving/issues/912

**Comment by lionelvillard** [comment]
can we leverage this code: https://github.com/kubernetes-sigs/controller-tools/tree/master/pkg/crd ?
