### ISSUE TITLE
genreconciler should be able to override the controller agent name

### ISSUE THREAD

**Issue by dprotaso** [knative/pkg#1137]
## Expected Behavior
The [Serving's GC reconciler](https://github.com/knative/serving/blob/b79fef014aaf1dd7bc06574cd2bfdc08a2aaad0f/pkg/reconciler/gc/controller.go#L36) has a controller agent name of [configuration-controller](https://github.com/knative/serving/blob/master/pkg/client/injection/reconciler/serving/v1/configuration/controller.go#L38)

It's used in the event broadcaster [here](https://github.com/knative/serving/blob/master/pkg/client/injection/reconciler/serving/v1/configuration/controller.go#L67) which makes the source of the events confusing.

## Actual Behavior
We should be able to override the the controller agent name so side-effects (logs & events) are have a clear origin

**Comment by andrew-su** [comment]
/reopen

The change is only in pkg right now, still need to be updated in serving

**Comment by dprotaso** [comment]
this was done in https://github.com/knative/serving/pull/7116
