### ISSUE TITLE
genreconciler should support Filtering

### ISSUE THREAD

**Issue by liu-cong** [knative/pkg#1149]
/kind feature

## Context
The eventing broker resource can have multiple controllers, each controlling a specific `brokerclass`. Ideally, we should apply filters for the `brokerclass` so that only interested broker objects are enqueued to a specific controller. 

However, the enqueue can be invoked by events of other resources such as an update in trigger, making it hard to apply the filter. Currently we apply the filter logic inside the `ReconcileKind` method, however the `Finalizer` is still added by the genreconciler. This means there could be multiple controllers competing to add the same `Finalizer` string.

See discussion in https://github.com/knative/eventing/pull/2737#discussion_r390026614

## Proposal
Using broker as an example:
Add a `FilterKind(ctx context.Context, o *v1alpha1.Broker) bool` interface. The genreconciler should call `FilterKind` and skip this object if it doesn't pass the filter.

cc @n3wscott @vaikas

**Comment by vaikas** [comment]
It should already work?
https://github.com/knative/pkg/tree/master/injection#annotation-based-class-filters

**Comment by liu-cong** [comment]
The annotation based filter can solve the broker problem with an caveat: https://github.com/knative/eventing/pull/2737#discussion_r390661347

However, I still think the `FilterKind` approach is desired since it solves a generic filtering problem.
