### ISSUE TITLE
[HA] Should have no downtime when active component is gracefully terminated

### ISSUE THREAD

**Issue by lionelvillard** [knative/pkg#1199]
/kind feature

## Expected Behavior

When a component is HA enabled and when the active component is gracefully terminated, the passive component should become active before the actual termination of the active component.

## Actual Behavior

There is some downtime before the passive or a new active component is back online.

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by mattmoor** [comment]
Maybe this could be achieved for rollout, but it doesn't seem practical for failover cases.

**Comment by markusthoemmes** [comment]
I *think* that's what `ReleaseOnCancel` in the `RunOrDie` config is for!

> // ReleaseOnCancel should be set true if the lock should be released
	// when the run context is cancelled. If you set this to true, you must
	// ensure all code guarded by this lease has successfully completed
	// prior to cancelling the context, or you may have two processes
	// simultaneously acting on the critical path.

So we "just" need to make sure that on context cancel, all of our code is done. Maybe we can construct another context that guarantees that, i.e. is deferred in the "run" method itself as the base context here is cancelled on signal, which is likely too early.

**Comment by lionelvillard** [comment]
@markusthoemmes Do you have cycles to look at this in more details?

**Comment by mattmoor** [comment]
https://github.com/knative/pkg/issues/1181 👀

**Comment by markusthoemmes** [comment]
Found some time to look at this.

1. "Fix" is here: #1229
2. The actual early release is currently broken due to kubernetes/kubernetes#88192.

**Comment by lionelvillard** [comment]
Thanks @markusthoemmes! When the lease is released, does the active component wait for the passive component to become active?

**Comment by markusthoemmes** [comment]
Shouldn't no. I think it just kicks the lease and thus forces the passive component to immediately go check it and reelect.

**Comment by mattmoor** [comment]
@markusthoemmes so is this done?
