### ISSUE TITLE
Validating Webhook Configuration rules should include callback operations 

### ISSUE THREAD

**Issue by juliaguo** [knative/pkg#1207]
## Expected Behavior
The `Rules` field in `ValidatingWebhookConfiguration` should include additional verbs supported in callbacks (such as the `Delete` operation), along with the default verbs `Create` and `Update`.

## Actual Behavior
The `ValidatingWebhookConfiguration` only contains rules for `Create` and `Update`, so requests with a `Delete` operation are never validated even if they have a callback.

## Steps to Reproduce the Problem

1. Create a validating admission controller that includes a callback to validate a CRD on deletion
2. Send a `DELETE` request to that CRD
3. No validation occurs

## Additional Info
I believe this can be fixed by passing in the supported verbs in each `Callback` to the `reconcileValidatingWebhook` method: https://github.com/knative/pkg/blob/master/webhook/resourcesemantics/validation/reconcile_config.go#L89
That way, if a callback supports a Delete operation, the webhook configuration can include the Delete operation in its `Rules` list. Otherwise, Delete requests would be filtered out before reaching the callback.

I got the impression that delete validations are currently intended to be supported, based on the handling of the Delete operation in the callback logic: https://github.com/knative/pkg/blob/master/webhook/resourcesemantics/validation/validation_admit.go#L184

**Comment by mattmoor** [comment]
What does it mean to validate a CRD you are deleting?

Is the objective to allow the `Validate(ctx)` function to inspect the context, see DELETE and disallow the deletion?

**Comment by vagababov** [comment]
Perhaps additional side actions?

**Comment by juliaguo** [comment]
For this issue, I was just focusing on the fact that requests with a Delete operation never make it to the callback step (even though callbacks handle delete operations) because the webhook config rules currently filter out all requests besides Creates and Deletes. I wanted to validate a CRD using a callback function I defined, blocking the deletion if a condition on the CRD is true. I could also see using the `Validate(ctx)` function to handle validating deletions there, but for this issue I was just hoping the bug on callbacks could be fixed.

**Comment by juliaguo** [comment]
This issue was fixed in #1219
