### ISSUE TITLE
[webhook] logs include raw bytes for patches

### ISSUE THREAD

**Issue by dprotaso** [knative/pkg#1222]
See: ```webhook/admission.go:93```

**Comment by shashwathi** [comment]
@dprotaso : Is there value in printing all fields in `reviewResponse ` object?

We are asking this to see if we should proceed with just eliminating Patch field or iterate through individual fields and print the value to retain current behaviour ?

**Comment by dprotaso** [comment]
I guess my intent for the issue was to print the string representation of the patch
