### ISSUE TITLE
genreconciler should be able to override the finalizer name

### ISSUE THREAD

**Issue by lionelvillard** [knative/pkg#1227]
## Expected Behavior

The MT GitHub source sets 2 finalizers, one by the control-plane component to delete the external webhook and one by the data-plane component to make sure the internal cache is properly synchronized.

## Actual Behavior

Only one finalizer can be set.

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by lionelvillard** [comment]
@n3wscott @mattmoor what do you think would be the best way to implement this feature?

For now I'm thinking of adding a new field (eg  `finalizerName`) in the generated `reconcilerImpl`. This field would be added only when the genreconciler is configured, via a gen tag, to allow overriding the finalizer name.

**Comment by markusthoemmes** [comment]
I have a similar need: I have a downstream reconciler that reconciles ingresses in parallel to one of the net-* reconcilers. My downstream reconciler adds another finalizer though to make sure it can clean up correctly as well.

I though about going a slightly different route than @lionelvillard though: Could we add a "FinalizerName" field to the reconcilerImpl that defaults to the default value and can be overridden via a controller option?

**Comment by markusthoemmes** [comment]
Cooked up a prototype over in #1230.

**Comment by lionelvillard** [comment]
To be clear, the only role of the gen tag is to generate the `FinalizerName` field, not to set its value. I personally think this tag not needed and I'm happy to always have the `FinalizerName` field in `reconcilerImpl`.
