### ISSUE TITLE
Implement retryable API events in injected Reconcilers

### ISSUE THREAD

**Issue by antoineco** [knative/pkg#1266]
/area API
/kind feature

I like the way generated Reconcilers can extract an event from the returned error and record that event via the injected EventRecorder. 👍 

Unfortunately, there is no way to return an "error" event _and_ retry the reconciliation. What I want is to be able to return an actual error while still being able to provide a better classification than "InternalError".

I suggest we support wrapping events inside a specific error type, similarly to how `controller.NewPermanentError` creates a special type of error, and take that as a hint that the reconciliation should be retried after the event is recorded.

I'm gonna look into this over the weekend unless someone objects.

/assign

**Comment by mattmoor** [comment]
cc @n3wscott 

This sounds reasonable to me :D
