### ISSUE TITLE
bump k8s to 1.18

### ISSUE THREAD

**Issue by zroubalik** [knative/pkg#1280]
Is there a plan to bump k8s version to 1.18 in near future? Signatures on methods in generated clientsets, dynamic,... clients have been modified to include `context.Context`.

## Additional Info
https://v1-18.docs.kubernetes.io/docs/setup/release/notes/#client-go

**Comment by nickgerace** [comment]
Would like to bump this if that's alright. Hitting this issue when updating client-go in some repos.

**Comment by vagababov** [comment]
We're now at 16, should we first go 17?

**Comment by nickgerace** [comment]
If it's possible, 18 would be great. The [Tekton Pipeline release v0.12.0](https://github.com/tektoncd/pipeline/releases) uses 18, which caused build failures when using their API due to its dependency on knative/pkg.

Granted, that's an issue to file with Tekton, not knative/pkg in particular. Just thought I'd mention it for context.

**Comment by dprotaso** [comment]
We've technically _just_ bumped our K8s dependency to 1.16/1.17 for the next release.

Although our [release principals](https://knative.dev/community/contributing/mechanics/release-versioning-principles/) mention we should be on 1.18 for the next release the reality is most providers don't offer it in stable release channels. 

ie. GKE stable is only on 1.16. EKS is 1.16, Azure will GA 1.17 in July.

So I don't think we're able to bump to 1.18 till it's more widely available

**Comment by tcnghia** [comment]
@dprotaso @mattmoor it's been two months since https://github.com/knative/pkg/issues/1280#issuecomment-646654370. 
 Has this changed? What is the latest client-go we can use?

**Comment by mattmoor** [comment]
I think we should consider migrating to the .18 client libs to start paying down the `ctx` migration costs, even if we're stuck at a 1.16 minimum version for now.  We can soft-bump to 1.17 like we did going to 1.16.

EKS definitely has 1.17, AKS probably does, and GKE has it in Rapid, so I'm hopeful that 1.17 will at least be available when we cut our .18 (that's not gonna be confusing!)

**Comment by mattmoor** [comment]
@mflendrich I have knative/networking staged in a PR, I think we'll try to land all of these tomorrow.

**Comment by mattmoor** [comment]
See: https://github.com/knative/networking/pull/152
