### ISSUE TITLE
Source metrics does not support reporting client error 

### ISSUE THREAD

**Issue by lionelvillard** [knative/pkg#1281]
## Expected Behavior
The source stats reporter should have tags for representing client errors (eg. when `http.Client.Do()` returns an error, or other client, like Kafka...).

## Actual Behavior
No such tags.

**Comment by n3wscott** [comment]
why is this in PKG?

we do this already in eventing: https://github.com/knative/eventing/blob/master/pkg/adapter/v2/cloudevents.go#L113

**Comment by lionelvillard** [comment]
this is adding additional metric labels. The current code does not generate stats all kind of errors, like timeout.

See https://github.com/knative/eventing/pull/3081 for more details.
