### ISSUE TITLE
Support Informer Injection with Wire

### ISSUE THREAD

**Issue by ian-mi** [knative/pkg#1286]
It would be useful to support injecting informers using a dependency injection system such as wire instead of through context.

### Benefits of Supporting a Dependency Injection Framework
- The context injection relies on init based registration which adds action at a distance. It is easy, for example, to introduce a dependency in a data plane component on a reconciler constant and start a number of unnecessary informers in that component due to the added import. It is also difficult to determine by examination which informers a component will start.
- Supporting a dependency injection framework would allow for other components, even other reconcilers, to be injected into controllers alongside the informers.

### Why Wire
Wire uses code generation so the dependency graph is verified at code generation time, not runtime, and it is easy to determine what the generated code is doing and what informers or informer factories are being created.

**Comment by vagababov** [comment]
Oooh, it's spring :)
