### ISSUE TITLE
allow for webhooks to exclude certain namespaces

### ISSUE THREAD

**Issue by duglin** [knative/pkg#1379]
**Problem**
Some webhooks such as: https://github.com/knative/eventing-contrib/blob/master/kafka/source/config/500-webhook-configuration.yaml#L18 do not limit themselves to just certain namespaces. This can be problematic if that webhook is acting up (e.g. the service is not responding), and the request that is being processed is not related to Knative at all but instead could be something critical such as being part of a system upgrade.

One options we discussed today is to define a label that can be added to any namespace such that the Knative webhooks could then be defined to exclude any namespace that has that label. For example, an admin could add the label to all Kube system namespaces to ensure that knative webhooks are never called for system related resource operations.

This technically isn't just an eventing issue, but since this is the first webhook I found with this problem I picked on it as a testcase and if we can find a solution that works for this one then we can consider applying it to all Knative webhooks.

( https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements )

/cc @mattmoor @mpetason

**Comment by mattmoor** [comment]
Moving to knative/pkg.

**Comment by duglin** [comment]
yup - I'd look at a "not" selector though since I doubt we can rely on people adding it to all NSs - so more of an opt-out model.

**Comment by mattmoor** [comment]
> This can be problematic if that webhook is acting up

I suspect that enabling HA webhooks that can be horizontally scaled would help here too.  I'm hoping we get that in for 0.16: https://docs.google.com/document/d/1emXelQiY0-cItq78QF5ZPvfpT6LD3KwXT0sCWM5cLy0/edit#

**Comment by duglin** [comment]
Help yes, but I think it's not a guarantee if the containers keep doing something like crashing.  I'm not 100% sure but I think we've seen cases where the containers kept OOM'ing and we had a heck of time recovering.

**Comment by mattmoor** [comment]
Ack, I'm just saying the most common reason for the webhook being down is rolling out a new version since we run a single pod that prior to 0.15 didn't have any readiness mechanism to drain gracefully.  😉

**Comment by dprotaso** [comment]
Should we always exclude `kube-system`?
