### ISSUE TITLE
Change log level to debug in admission webhook response details

### ISSUE THREAD

**Issue by toVersus** [knative/pkg#1397]
I'm building my own mutating webhook based on [knative webhook library](https://github.com/knative/pkg/tree/master/webhook), which injects the sensitive data from external secret store to K8s Secret object. I like the idea of generating/rotating CA and server certificates for webhook on its own and currently it's working as expected. However, I'm unhappy with the admission log output, which contains the raw sensitive data. Can we change the log level from `info` to `debug` only at this part? If so, I will submit a PR.

https://github.com/knative/pkg/blob/fef70cc2616b2937d13a1aed2b9f8b539c43c768/webhook/admission.go#L98-L100

**Comment by nak3** [comment]
I think that the change makes sense.

@evankanderson @dprotaso @antoineco What do you think? It is different reason but similar to another request on slack https://knative.slack.com/archives/C93E33SN8/p1595308110264500

**Comment by evankanderson** [comment]
I think it makes sense to cast a critical eye at our logging in general, which is pretty noisy in the "happy case" when things are stable.

**Comment by dprotaso** [comment]
> Can we change the log level from info to debug only at this part? If so, I will submit a PR.

Feel free to change the level.  Another option may be to reduce the properties being logged on Info and include them on debug.

**Comment by nak3** [comment]
@toVersus would you mind working on it?

/assign @toVersus
