### ISSUE TITLE
We should always InitializeConditions when reconciling 

### ISSUE THREAD

**Issue by dprotaso** [knative/pkg#1401]
## Expected Behavior

We need to initialize conditions prior to reconciling in case new conditions are added/defaulted across releases

## Actual Behavior

We actually skip initializing conditions if gen == observed gen 
https://github.com/knative/pkg/blob/2ddcfef739a2e0ad5af446bffa0ecd6ce49b760e/reconciler/reconcile_common.go#L29-L41

**Comment by whaught** [comment]
Do we also want to move defaulting here and do it for all resources?
