### ISSUE TITLE
Provide More Details in Error Message for Decoding Errors

### ISSUE THREAD

**Issue by danielhelfand** [knative/pkg#1414]
Classify what kind of issue this is:

/kind question
/kind feature

## Expected Behavior

As detailed in https://github.com/knative/eventing/issues/2714, the error message from [`defaulting.go`](https://github.com/knative/pkg/blob/086ff43956418f32abedde99deb4fab952de69f5/webhook/resourcesemantics/defaulting/defaulting.go#L231) for decoding can produce an error that could provide more detail to help a user fix a resource definition. 

An example being where multiple properties are specified but only one use of the property is invalid. Providing more detail on where the error is occurring would be helpful in this scenario. 

## Actual Behavior

Error message returned provides only details on what properties have failed validation, but doesn't provide further details, such as in the example in the issue outlined for eventing.

**Comment by vagababov** [comment]
The error is returned by the parser, which is standard library, which I think stops at the first error.

**Comment by danielhelfand** [comment]
Sure, think it makes sense as far as sticking with the standard library error, but wondering if augmenting with, for instance, a line number would be worthwhile.

**Comment by vagababov** [comment]
But that means we need to get the line number. What will provide it?

**Comment by danielhelfand** [comment]
Yeah, maybe the better route would be some other tool like kn to validate resources before being created or after an error occurs. But to your point, there isn’t much more additional context that could be provided here.
