### ISSUE TITLE
We should inject a fake clock and mock Now()

### ISSUE THREAD

**Issue by whaught** [knative/pkg#1461]
## Problem
We have used VolatileTime to ensure condition times are kept stable and are not considered for equality. This makes testing easier, but it is difficult to ensure times are really being stamped at all.

In our unit tests we do occasionally mark other timestamps. Eg:
https://github.com/knative/serving/blob/24d679dcb8d62f87b68bdb17abe894540bf046e3/pkg/reconciler/labeler/labeler_test.go#L50

In this case we are setting ObjectMeta.DeletionTimestamp which is a metav1.Time, not a VolatileTime. This test relies on it executing fast enough that the clock will not have changed - this leads to occasional flake.

## Solution
We should either
1. Inject time.Now() onto the context such that reconcilers are all using the same timestamp for this reconciliation.
2. Create an interface for retrieving Now() that either is a time or is a fakeTime where unit tests could set a value.

**Comment by whaught** [comment]
I found a neat workaround

In the code:
var nowFunc = time.Now

In the test:
nowFunc = func() time.Time { return mockedResponse }

We could go further, but this works for now.

**Comment by vagababov** [comment]
We should use k8s.io/apimachinery/pkg/util/clock/clock.go (and its test equivalents) and inject it into the constructor.
We _do_ that in a few places, I think.

**Comment by vagababov** [comment]
e.g. https://github.com/knative/serving/blob/master/pkg/reconciler/route/controller.go#L58

**Comment by whaught** [comment]
Oh cool! I might look into that if its a canonical solution
