### ISSUE TITLE
AllowCustomMetrics=false and custom metrics are emitted

### ISSUE THREAD

**Issue by JRBANCEL** [knative/pkg#1470]
# Or OpenCensus doesn't work as you think it does

## Expected Behavior
When `metrics.backend-destination` in `ConfigMap` is set to `stackdriver` and `metrics.allow-stackdriver-custom-metrics` is either not set or set to `false`, I am expecting no custom metrics to be emitted (e.g. `go_alloc`).

## Actual Behavior
These metrics are emitted.

### Scenario 1
If a Pod (let's say Activator) starts and `metrics.backend-destination` is set to `stackdriver`, then those metrics are not emitted.

### Scenario 2
If a Pod starts and `metrics.backend-destination` is set to `prometheus`, and then changed to `stackdriver`, the metrics are emitted.

### Why?
OpenCensus doesn't work as `knative.dev/pkg/metrics` assumes it does. Swapping exporters and filtering calls to `Report` is not enough.

For example, for `go_alloc`, a `Measure` is created, and that `Measure` is associated to a `View` and that `View` is registered to the system. In this case the `View` has an aggregation of type `LastValue`, meaning that when the exporter periodically asks the `View` for the value to export, the last value reported using the `Measure` will be returned.

An aggregation of type `LastValue` doesn't return anything if no value was ever reported, so the exporter doesn't export anything for that view (a.k.a metric) in that case.

### Scenario 1
`metrics.backend-destination` is set to `stackdriver` and there is [some logic](https://github.com/knative/serving/blob/77c03f0f6f5f86b0cfe5023786351974403276ec/vendor/knative.dev/pkg/metrics/config.go#L263) to filter out those metrics if `allowCustomMetrics` is `false`. In this case, when `Report` is called for `go_alloc`, the call never ends up going to the corresponding `Measure` and therefore the corresponding `View` always return nothing to the exporter and nothing is exported.

### Scenario 2
`metrics.backend-destination` is set to `prometheus` and there is [no logic](https://github.com/knative/serving/blob/77c03f0f6f5f86b0cfe5023786351974403276ec/vendor/knative.dev/pkg/metrics/config.go#L165) to filter out these metrics, so a call to `Report` ends up going to the `Measure` and to the `Aggregator`.
At some point, `metrics.backend-destination` is set to `stackdriver`. As explained in *Scenario 1*, from that moment on, the filtering logic will prevent any call to `Report` to end up reaching the corresponding `Aggregator`, **BUT** that `Aggregator` still stores a value (the last one reported before switching to `stackdriver`) and that value will be returned to the exporter when it periodically scans the views. 

As a result, that last reported value before switching to `stackdriver` will be perpetually emitted.   

## Workaround
Configure `config-observability` before creating the `knative-serving` `Deployments`.
Or reboot the Pod after changing `config-observability`.

## Fix
The views corresponding to the custom metrics should be unsubscribed from the system when we don't want them to be emitted. It is vastly cleaner and more efficient than the manual filtering done at every call to `Report`.

**Comment by evankanderson** [comment]
/assign @evankanderson @MontyCarter 

I'm wondering whether the hot-reload of ConfigMaps for metrics is worth it, but I'd love to get an additional opinion.

**Comment by evankanderson** [comment]
Another option would be to actually wrap / reimplement the stackdriver export, since the "custom metrics" feature only applies for stackdriver (IIRC, this was because on Google's product, certain metrics are provided gratis, and all additional metrics are paid-for).

**Comment by MontyCarter** [comment]
> /assign @evankanderson @MontyCarter
> 
> I'm wondering whether the hot-reload of ConfigMaps for metrics is worth it, but I'd love to get an additional opinion.

If I don't misunderstand your suggestion, I think it's kind of unpolished without the config hot reload, and is inconsistent with user expectations (if I change the config, the configuration should change...).  With that said, I wouldn't expect this to get changed for most customers of products built on top of knative (though maybe for OSS users - though these users will expect a little less hand holding).

Getting rid of hot reload means that customers will need to manually restart all knative-serving pods, plus all of their user-container workloads.  This seems like a pretty poor experience to me.

I think modifying stackdriver export would be an ok solution, as it confines the exceptional custom metrics code to just stackdriver.

However, perhaps the idea I like best is waiting till Google has an otel collector service in place, at which point we can do all of the filtering on the collector service.  We could then remove custom metrics from knative altogether.
