### ISSUE TITLE
logstream doesn't work with HPA or chaos

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#1488]
/area API
/area monitoring
/area test-and-release
/kind bug

## Expected Behavior

`logstream` should pick up new system pods and start streaming their logs.

## Actual Behavior

`logstream` doesn't pick up new logs (HPA) and often stops logging altogether when run with chaos.

## Crux

The crux of the issue is that pods are only listed at startup, so as pods are retired and new ones brought up over the course of the test the logging simply falls off.

See here: https://github.com/knative/pkg/blob/16eea5bd5b12aeef02a696d73f3661da627e2726/test/logstream/kubelogs.go#L61

**Comment by vagababov** [comment]
/close
This is done and should be merged to serving here https://github.com/knative/serving/pull/8643
