### ISSUE TITLE
Serving `Generating ...` takes a long time on my not the weakest machines.

### ISSUE THREAD

**Issue by vagababov** [knative/pkg#1489]
To run `./hack/update-codegen.sh` on serving takes a few minutes. I'd expect O(seconds).
Which seems _a bit_ high. Is there anything we can improve there?

/cc @n3wscott @mattmoor

**Comment by markusthoemmes** [comment]
ack, I always comment out the entire file when working on just protobufs. Or use the call to go make a fresh cup of coffee :joy:

**Comment by vagababov** [comment]
I found that I get distracted so much, that my ssh connection usually breaks :)

**Comment by vagababov** [comment]
/remove-lifecycle stale
/cc @julz 
as discussed recently
