### ISSUE TITLE
Implement a workqueue "slow lane".

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#1505]
/area API
/kind feature

Today our shared controller infrastructure uses a `workqueue.RateLimitingInterface` to manage keys ([here](https://github.com/knative/pkg/blob/096656a2d4c88b8d6030feb2384da1d347fb3ccf/controller/controller.go#L189-L194)).

Most of the stuff that we stick onto the queue is driven by informer events, which point to specific resources and result in a single key being queued, e.g. via [EnqueueKey](https://github.com/knative/pkg/blob/096656a2d4c88b8d6030feb2384da1d347fb3ccf/controller/controller.go#L346-L350), and occasionally we'll snooze a resource through a mechanism like [EnqueueKeyAfter](https://github.com/knative/pkg/blob/096656a2d4c88b8d6030feb2384da1d347fb3ccf/controller/controller.go#L360-L365).

However, there are global events, which may prompt us to reconsider *everything* in our key space, e.g. changing a controller's configmap.  We refer to these as "global resyncs" and we have a [GlobalResync](https://github.com/knative/pkg/blob/096656a2d4c88b8d6030feb2384da1d347fb3ccf/controller/controller.go#L495-L499) method that helps us manage these.

One of the problems we hit with global resyncs was that they "just" queued all resources for reconciliation, which is mostly what we want, but the problem is that many of these resyncs may be benign and when we're talking about 100s or 1000s of keys they clog up the workqueue preventing other work that's queued due to informer events from being processed in a timely fashion.

Historically we've worked around this by having global resyncs `EnqueueAfter` with a jitter factor based on the size of the resync, which helps distribute the keys of the global resync over some period of time.  However, this means that it could take us 100s to resync 100 keys even if no other work is being done, and the adequately jitter these we need a pretty global view of the resync being performed.

---

The basic idea behind this issue is that instead of jittering, we would simply place keys knowingly enqueued due to a resync event onto a "slow lane", either internal to the workqueue or as a second workqueue.

Traditional queuing events would push work onto the "fast lane", and explicit resync events (e.g. global resync, [failover](https://github.com/knative/pkg/pull/1504)) would push work onto the "slow lane".

This enables us to keep processing "slow lane" keys when the "fast lane" is empty, while also doing a better job of keeping "slow lane" keys from getting in the way of keys that have actually seen an informer event.

**Comment by mattmoor** [comment]
See also what we found [here](https://github.com/knative/eventing/issues/3591#issuecomment-659015098)

**Comment by lionelvillard** [comment]
it seems what's you need a priority workqueue?

**Comment by mattmoor** [comment]
@lionelvillard that would work too, but I suspect we'd only use a handful of discrete priorities.

Where I'm torn here it between defining out own workqueue interface extension to allow for prioritization and juggling two workqueues.
