### ISSUE TITLE
Should we be creating events for successful modification of finalizers?

### ISSUE THREAD

**Issue by vaikas** [knative/pkg#1539]
As we've been enabling chaos and going through various Events with various controllers, I was wondering if we really want to be emitting events for when we modify finalizers. I think we should emit on failures, I'm thinking about emitting events during success?

For example here:
https://github.com/knative/eventing/blob/master/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go#L410

**Comment by mattmoor** [comment]
I think it's probably overkill, but they are sparse enough that it probably doesn't matter.

**Comment by evankanderson** [comment]
The [Kubernetes API Convertions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#events) suggest:

> Generate events for situations users or administrators should be alerted about.

I suspect "normal" addition (and possibly removal) of a finalizer doesn't cross the bar of "a user wants to see this in `kubectl describe` output".
