### ISSUE TITLE
Automatically set GOMAXPROCS in sharedmain

### ISSUE THREAD

**Issue by julz** [knative/pkg#1583]
## Expected Behavior

GOMAXPROCS for controllers is correctly set when deployed in a container with a cpu limit.

## Actual Behavior

Container GOMAXPROCS are set as if they have access to all the cpus on the host

## Steps to Reproduce the Problem

1. Deploy e.g. knative serving
2. Check GOMAXPROCS of e.g. autoscaler (which has [cpu limit of 300m](https://github.com/knative/serving/blob/master/config/core/deployments/autoscaler.yaml#L47) = less than 1 cpu)
3. See that GOMAXPROCS is set to number of CPUs on host :-( (on my Minikube with 10 CPUs, it's set to 10).

## Some context/other threads:

- https://github.com/golang/go/issues/33803 (Golang issue)
- https://github.com/prometheus/prometheus/issues/6413
- https://github.com/istio/istio/issues/20264

## Proposed solution:

We could use something like https://github.com/uber-go/automaxprocs to fix this. Or we could explicitly set GOMAXPROCS env variable in our yamls to match set quotas, but that won't work well if operators change the limits. Or we could wait for upstream Go to fix this (See linked issue above), but it looks like this is no longer landing soon.

**I think personally https://github.com/uber-go/automaxprocs seems like a reasonable approach here since it copes better with someone using the operator to bump cpu quotas, but would like to see if anyone has concerns with that before PRing :-)**

/assign @vagababov @markusthoemmes mattmoor

**Comment by vagababov** [comment]
well, since you assigned to me — me gonna just do it? 😃 
This seems reasonable enough to just use automaxprocs, until golang is fixed itself.

**Comment by julz** [comment]
ha! well I have a PR ready, I was assigning for people to tell me it's a bad idea before I send it :)

**Comment by julz** [comment]
Pushed the PR :) https://github.com/knative/pkg/pull/1585

**Comment by vagababov** [comment]
💭
