### ISSUE TITLE
log status changes under codegen at debug

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#1597]
/area API
/kind feature
/kind good-first-issue

I think that it would be a phenomenally useful debugging tool to have the codegen `logger.Debugf` the `kmp.SafeDiff` of the status updated it performs.

With logstream, this should give us a nearly perfect record of the state transitions all test resources make over the course of a test.

cc @n3wscott @whaught @vagababov @markusthoemmes

**Comment by whaught** [comment]
This would be a lot more useful that some of the existing logging that just writes on every execution (and tends to pollute the logs). eg: [dumping the route object on every reconcile](https://github.com/knative/serving/blob/e0107189599f1285db77f18dcafe9060b2f462b1/pkg/reconciler/route/route.go#L108)

**Comment by mattmoor** [comment]
... and consistent and free!  😎 

This used to be in our boilerplate (pre-codegen) I don't recall why we removed it.

**Comment by n3wscott** [comment]
An overall pass of log levels in this code and adding trace and debug levels would be a huge help. They are a little too chatty at normal level and not enough chatty to debug weird stuff. 

Sgtm

**Comment by mattmoor** [comment]
I may send a PR for this shortly, if I don't run into any unexpected problems :)
