### ISSUE TITLE
webhook-certs data is not created

### ISSUE THREAD

**Issue by arief-hidayat** [knative/pkg#1641]
## Expected Behavior
all pods including webhook pod should be running.

## Actual Behavior
webhook pod can't run due to `server key missing`
```
2020/08/23 16:23:22 http: TLS handshake error from 10.250.22.195:59268: server key missing
...
```

This could be due to `webhook-certs` data is not getting updated as it should be.
```
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "v0.17.0"
# The data is populated at install time.
```

## Steps to Reproduce the Problem

apply knative-serving core from version 0.17.0
```
KNATIVE_VERSION=v0.17.0
curl -L https://github.com/knative/serving/releases/download/${KNATIVE_VERSION}/serving-crds.yaml > kubectl/01-knative-serving-crds.yaml
curl -L https://github.com/knative/serving/releases/download/${KNATIVE_VERSION}/serving-core.yaml > kubectl/02-knative-serving-core.yaml
```

## Additional Info

WebhookCertificates said `Reconcile succeeded` but `webhook-cert` is not updated with cert data.
```

{"level":"info","ts":"2020-08-23T16:23:21.643Z","logger":"webhook","caller":"leaderelection/context.go:134","msg":"webhook.webhookcertificates.00-of-01 will run in leader-elected mode with id \"webhook-85758f4589-kcn59_f14e6f6e-e220-42d6-95bd-f0789bdd8092\"","commit":"427b2bf"}
{"level":"info","ts":"2020-08-23T16:23:21.643Z","logger":"webhook.WebhookCertificates","caller":"controller/controller.go:444","msg":"Starting controller and workers","commit":"427b2bf"}
{"level":"info","ts":"2020-08-23T16:23:21.643Z","logger":"webhook.WebhookCertificates","caller":"controller/controller.go:454","msg":"Started workers","commit":"427b2bf"}
{"level":"info","ts":"2020-08-23T16:23:21.643Z","logger":"webhook.WebhookCertificates","caller":"controller/controller.go:520","msg":"Reconcile succeeded. Time taken: 4.718µs","commit":"427b2bf","knative.dev/traceid":"31c4416c-2ff7-4a54-bfe7-e9d5756c5f1f","knative.dev/key":"knative-serving/webhook-certs"}
```

**Comment by arief-hidayat** [comment]
I confirm the above issue is fixed when I add  `--disable-ha`
```
       containers:
       - args:
         - --disable-ha
```

**Comment by slinkydeveloper** [comment]
A complete reproducer using kafka channel webhook https://github.com/knative/eventing-contrib/issues/1554#issuecomment-692342180

**Comment by slinkydeveloper** [comment]
@pmorie any idea how ha is impacting on webhook certs?

**Comment by mattmoor** [comment]
Judging from the linked eventing issue, I think this is a bad interaction with the liveness probe.

This was [recently changed](https://github.com/knative/serving/pull/9215) in Serving to double the number of liveness probes needed to fail before restarting the process, but a `periodSeconds: 1` and defaults means the container has 3s to be up and functionally serving HTTPS, which is probably not very realistic.

Here's the kafka-channel config: https://github.com/knative/eventing-contrib/blob/096b0925bf501a42db28b760152b302b80dccd11/kafka/channel/config/deployments/webhook.yaml#L69

Here's the (new) serving config (6 attempts): https://github.com/knative/serving/blob/64a83f80930bd85a50fabac28bfa1b662d978b4a/config/core/deployments/webhook.yaml#L105

I still think 6s is probably a bit low for initial installation flow, which requires the pod to boot up, sync informers, become leader, promote the bucket (resync TLS key), get back the TLS key via informer watch, and serve a successful liveness probe.

One other note on why 3 (and even 6) feels low:  The default leader election retry period is 2s.

I sort of think that we want `initialDelaySeconds: 10` or so on the liveness probes as well.


cc @julz @markusthoemmes @tcnghia
