### ISSUE TITLE
Metrics: add string constants to be referenced by other packages.

### ISSUE THREAD

**Issue by jjzeng-seattle** [knative/pkg#1645]
/kind good-first-issue
/kind cleanup
/area monitoring

In metrics pkg there are some places we use string literals to refer fields in config, and then use the same strings in other packages.
For example:  https://github.com/knative/pkg/blob/8ae01327905dab7dc0afe9319d8c91ccd2485f4b/metrics/config_observability.go#L90
and then the field is referenced in serving.

We should convert the strings into exported consts to avoid typo and make it easier to refactor/rename.

**Comment by jjzeng-seattle** [comment]
Another example is https://github.com/knative/pkg/blob/8ae01327905dab7dc0afe9319d8c91ccd2485f4b/metrics/config_observability.go#L84
and https://github.com/knative/pkg/blob/8ae01327905dab7dc0afe9319d8c91ccd2485f4b/metrics/config_observability.go#L87

Maybe we should just convert this whole block.

**Comment by NEERAJAP2001** [comment]
@jjzeng-seattle sir, can you give up a code-sample so that I can work on. (I'm new to open source)
