### ISSUE TITLE
Clean up duplicated values in pkg repo and networking repo

### ISSUE THREAD

**Issue by nak3** [knative/pkg#1679]
Select the appropriate areas for your issue:

/area networking
/kind cleanup

## Actual Behavior

Some values in `network/network.go` is duplicated in networking repo's `pkg/network.go`. 
For example,  `ProbeHeaderName` is defined in both pkg repo and networking repo.

in pkg repo:

https://github.com/knative/pkg/blob/67e9bcf967f76db4e662685832ddaf0cc374fc17/network/network.go#L55

in networking repo:
https://github.com/knative/networking/blob/80398434dcd45c7e359dee4ae4e8986e191464fc/pkg/network.go#L44

**Comment by vagababov** [comment]
So this is not just removing a few constants.
There's more code in pkg that should be moved to networking first
- drain handler
- error handler

More things to be removed like probe handlers....
I'll try to sort this out.
