### ISSUE TITLE
Allow override QPS and Burst via flag

### ISSUE THREAD

**Issue by pierDipi** [knative/pkg#1700]
The `sharedmain` package doesn't allow overriding client QPS and Burst via a flag and this forces doing convoluted logic to override it:

```golang
	clientQPS := flag.Float64("clientQPS", float64(rest.DefaultQPS), "Overrides rest.Config.DefaultQPS.")
	clientBurst := flag.Int("clientBurst", rest.DefaultBurst, "Overrides rest.Config.Burst.")

	cfg := sharedmain.ParseAndGetConfigOrDie()

	cfg.QPS = float32(*clientQPS)
	cfg.Burst = *clientBurst
```

Also, this allows having a standardized way of configuring QPS and burst for all controllers.

## Proposal

- `--kube-api-qps <float32>` flag sets `Config.QPS`, default value `rest.DefaultQPS`
- `--kube-api-burst <int>` flag sets `Config.Burst`, default value `rest.DefaultBurst`

**Comment by kallyshall** [comment]
Or can these values be overrode through given env variable? 
I see now QPS and burst value can be given through kubeconfig file, but if in a shared cluster, the config will influence all containers within.

**Comment by pierDipi** [comment]
@mattmoor @dprotaso does this sound something acceptable?

**Comment by dprotaso** [comment]
I think what's non-obvious is that as new controllers are added to a binary the QPS/Burst changes - or at least it did I can't find the code.

> Also, this allows having a standardized way of configuring QPS and burst for all controllers.

So is this property global for all controllers or per controller?

**Comment by mattmoor** [comment]
I'm ok with adding a flag to control the QPS/Burst, we've needed such a thing a few times.  This gives folks recourse to increase these (without rebuilding things) when they hit problems.

That said, I don't think folks should expect to specify these in their steady state, since they are likely papering over some anti-pattern in their controller(s).

**Comment by pierDipi** [comment]
> I think what's non-obvious is that as new controllers are added to a binary the QPS/Burst changes - or at least it did I can't find the code.

The code you're referring is this:
https://github.com/knative/pkg/blob/247841408e57cb3788e3a200b78b7ace6ea808b0/injection/sharedmain/main.go#L219-L234
and I think we can keep this feature by setting the default value of the flag to 0.

> So is this property global for all controllers or per controller?

All controllers in a single process.

> I'm ok with adding a flag to control the QPS/Burst, we've needed such a thing a few times. This gives folks recourse to increase these (without rebuilding things) when they hit problems.
>
> That said, I don't think folks should expect to specify these in their steady state, since they are likely papering over some anti-pattern in their controller(s).

Agree, we added this in eventing to debug some chaos testing failures, and [Tekton's folks added those flags recently](https://github.com/tektoncd/pipeline/pull/3156), so upstreaming to pkg makes sense to me.
