### ISSUE TITLE
Allow customize DefaultThreadsPerController value

### ISSUE THREAD

**Issue by kallyshall** [knative/pkg#1708]
## Expected Behavior

The **DefaultThreadsPerController** value can be customized through passing flags like  #1700 suggested or environment variable.

## Actual Behavior

https://github.com/knative/pkg/blob/master/controller/controller.go#L53
```
var (
	// DefaultThreadsPerController is the number of threads to use
	// when processing the controller's workqueue.  Controller binaries
	// may adjust this process-wide default.  For finer control, invoke
	// Run on the controller directly.
	DefaultThreadsPerController = 2
)
```
Currently, this value is fixed and can not be modified without changing the code.

**Comment by vagababov** [comment]
It seems we had that before, but this seems reasonable in general.

**Comment by vagababov** [comment]
/assign
I'll try to look at it.

**Comment by kallyshall** [comment]
@vagababov thank you for looking at this.
I see now the QPS and burst value can be modified by changing kubeconfig file, but it will make these values have influence on every containers within cluster.

We have a shared cluster and just don't want to influence others, is it reasonable to customize the value using env variable, or by passing flags in deployment yaml : containers. args ?

**Comment by zhaojizhuang** [comment]
Is there any progress on this issue?

**Comment by kallyshall** [comment]
> Is there any progress on this issue?

no progress I think, since no current assignee
