### ISSUE TITLE
Correct error method for key collision?

### ISSUE THREAD

**Issue by ImJasonH** [knative/pkg#1726]
Consider this very common scenario:

```
kvs:
- name: foo
  value: hello
- name: foo
  value: world
```

In this scenario, `kvs` describes some key-value pairs (env vars, parameters, etc.), and the above config is invalid because two values are specified for the key `foo`. (It would _also_ be invalid even if both `foo`s had the same value)

Is there an error method in knative.dev/pkg/apis that I should use to signal this error? It looks like in Tekton-land we tend to use [`ErrMultipleOneOf`](https://godoc.org/knative.dev/pkg/apis#ErrMultipleOneOf) which is _definitely not correct_, but I don't see a good candidate to use instead.

If there isn't a method in knative.dev/pkg/apis, we could add something like `ErrKeyCollision` (bikeshed away!), and even if there is a method al ready, it might be worth adding something like a reflection-based helper method to process a slice of `Thing`s and a field name of the `Thing` type that should have a different value for each item in the slice-of-`Thing`s, and return `ErrKeyCollision` if there's a conflict.

WDYT?

/kind question
/area API

**Comment by vagababov** [comment]
` ErrInvalidKeyName` ? :)

**Comment by ImJasonH** [comment]
> ` ErrInvalidKeyName` ? :)

That's definitely an option, but I was hoping to find/build something a bit more tailor-made to the situation we see a lot of. From grepping knative/serving it looks like `ErrInvalidKeyName` seems to be mostly for invalid label/annotation keys, and less for KRM-style key-value pairs.

FWIW I've hacked up https://github.com/knative/pkg/compare/master...ImJasonH:err-key-collision to provide a `reflect`-based helper method, let me know if that's on the wrong path.

**Comment by vagababov** [comment]
Looks very adhoc built thingy :)
I.e. given we've never seen need for this so far (doesn't mean we won't of course) — why wouldn't it be downstream in some tekton/pkg/api/utils, or something there of :)

**Comment by vagababov** [comment]
As in, I am not against, but I am not sure that this is generic enough either.

**Comment by ImJasonH** [comment]
Yeah that's perfectly reasonable. I'll propose it over there and if anybody reading this wants it in knative/pkg let me know.
