### ISSUE TITLE
Have more control over finalizers

### ISSUE THREAD

**Issue by vaikas** [knative/pkg#1734]
## Expected Behavior
When using genreconciler for Trigger and if the controller (for example: knative-sandbox/eventing-rabbitmq) needs a finalizer (to clean up rabbit resources), it will then apply this finalizer to all the Trigger objects regardless of whether it's actually responsible for it or not.

It would be better to be able to control whether a finalizer is applied and which finalizer label is applied.

Talked with @n3wscott offline about this and perhaps we could introduce a new method that will be invoked by the genreconciler prior to applying a finalizer. Something like ShouldFinalize and if it's implemented, it can return a string that will be used as a finalizer and if empty string is returned it will not apply a finalizer.

**Comment by vaikas** [comment]
A workaround is to manually remove a finalizer if it's there in my reconcilekind.

**Comment by vaikas** [comment]
actually that doesn't seem to work...

**Comment by markusthoemmes** [comment]
Does it work if you use a filtered reconciler for this?

**Comment by vaikas** [comment]
I didn't think so because in order to figure out if the finalizer needs to be applied, I need to actually look up the Broker to see if I'm responsible for it. But, I'll take a closer look later :) Thanks for the suggestion.
