### ISSUE TITLE
Allow scaling controllers horizontally 

### ISSUE THREAD

**Issue by alan-ghelardi** [knative/pkg#1813]
How feasible would be somehow allowing controllers to be scaled horizontally? Currently, I am not a direct user of Knative APIs, but I am of Tekton ones and I'm realizing that in scenarios of high concurrency, the controller gets overloaded and the reconciliation loop gets slower. Perhaps, for cases like this one (and most likely, there might be other ones for different use cases of Knative controllers) scaling controller pods horizontally would be extremely helpful.

Are there plans to address this need?  

## Expected Behavior

Controllers must support a multileader election mechanism. 

## Actual Behavior

Controllers support a leader election mechanism where there's an active controller and passive ones, but it's not possible to have multiple instances acting in the reconciliation process simultaneously.
## Steps to Reproduce the Problem

1.
2.
3.

**Comment by vagababov** [comment]
The controllers (except for autoscaling with some limitations) are currently horizontally scalable in a fixed manner (i.e. you need to restart them to pick new scale and re-shard the resources).

**Comment by alan-ghelardi** [comment]
@vagababov  just to understand, you're saying that I could configure an arbitrary controller deployment to have two replicas and after restarting it, the two instances will split resources correctly? As far as I know, the leader election feature is enabled by default in Knative controllers and when they start up, one instance assumes the leadership while others remain inactive. Shall I disable the leader election in this case?

**Comment by vagababov** [comment]
No, the newer versions split the key space into buckets and each bucket is
independently master elected

**Comment by alan-ghelardi** [comment]
@vagababov  thank you so much for clarifying.
