### ISSUE TITLE
Decorate loggers with the controller name

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#1829]
/area API
/area monitoring
/kind cleanup
/kind feature
/kind good-first-issue

## Expected Behavior

The logger attached to the context supplied to `ReconcileKind` should be decorate with a controller name that uniquely identifies it.

Serving does this [here](https://github.com/knative/serving/blob/dfd2b8eab7d23e0bb2a8557fc1b4674fa32a3acd/pkg/reconciler/revision/controller.go#L70), but this should be built-in.

## Actual Behavior

Controller's that don't specify this end up with undecorated logs, which makes it challenging to filter on them in controllers with multiple reconcilers linked in.

**Comment by mattmoor** [comment]
cc @dprotaso @yanweiguo @vagababov @n3wscott

**Comment by vagababov** [comment]
👍

**Comment by vagababov** [comment]
I see this going two ways:
1. attach the reconciler name to the context and read it off to attach to the logger in one of the MainWithX
2. add a new interface that all the controllers can implement
     ```
     type Named interface {
       Name() string
     }
     
     // ....
     // In mainwithx.
     if n, ok :=rec.(Named); ok {
        name = n.Name()
        l := logging.FromContext(ctx)
        l = l.With("reconciler", name)
        ctx = logging.ToContext(l)
     }
     ```

**Comment by dprotaso** [comment]
I just saw serving's logger names are they're a bit .... something

`controller.route-controller.knative.dev-serving-pkg-reconciler-route.Reconciler`

**Comment by vagababov** [comment]
I think we do named a few times and zap aggregates them rather than replace

**Comment by dprotaso** [comment]
We also have structured fields ie. [`logkey.ControllerType`](https://github.com/knative/pkg/blob/51c72e24c179dc777b0228edf44bd4ef6eb94357/logging/logkey/constants.go#L21)

I guess we should decide whether to add context using:
1) `Named` (pro: succinct,  con: can't query, may not be stable)
2) `With` structured fields (pro: can query, con: verbose)


what we have now in serving is like
```json
{
   "level":"info",
   "ts":"2021-01-07T15:43:45.085Z",
   "logger":"controller.route-controller.knative.dev-serving-pkg-reconciler-route.Reconciler",
   "caller":"route/route.go:172",
   "msg":"Route successfully synced",
   "commit":"0a890ef",
   "knative.dev/pod":"controller-75b4d5c655-ndkxk",
   "knative.dev/controller":"route-controller",
   "knative.dev/traceid":"65b425f5-c76b-46ae-a9dc-7b84ece1a342",
   "knative.dev/key":"default/test-13981"
}
```

With `knative.dev/pod` we technically don't need the top level component name anymore ie. `controller`. `route-controller` appears in the ControllerType property so we don't need to name it.

What's unique to the logging name is the reflected type name `knative.dev-serving-pkg-reconciler-route.Reconciler"` which itself is a bit redundant. @n3wscott is the intent to know the implementation or object being reconciled?

**Comment by dprotaso** [comment]
I opt'd for structured fields see the PR
