### ISSUE TITLE
Controller Pods are too slow to become the new leader after the previous leader releases the ownership

### ISSUE THREAD

**Issue by yanweiguo** [knative/pkg#1835]
## Expected Behavior
We run leader election mode for Serving Autoscaler, Controller, Webhook. If there are multiple pods, one pod is expected to be take over the ownership of a bucket immediately after the previous leader pod releases the ownership.

## Actual Behavior
It could take more than 20 seconds for a bucket to be occupied by a new owner.

## Steps to Reproduce the Problem

1. Run `watch kubectl -n knative-serving get leases`.
2. Choose a lease and find its holder, get the pod name as the prefix and delete the pod.
3. Watch the outputs from step 1. It usually takes 15 seconds for the change with a new leader. 15 seconds is the default value of leaseDuration.

## Additional Info
I think we need to tweak https://github.com/knative/pkg/blob/master/leaderelection/config.go#L102

**Comment by yanweiguo** [comment]
cc @mattmoor

**Comment by lionelvillard** [comment]
@yanweiguo you may be hitting this bug: https://github.com/kubernetes/kubernetes/pull/91942. Eventing applies this PR after updating dependencies.

**Comment by mattmoor** [comment]
I think we pulled in the patch as well @lionelvillard, but I also thought it got pulled in and dropped with the latest K8s client update? 🤔 

@yanweiguo I'm surprised this wouldn't be causing problems since we kill leaders every 30s in most of our e2e scenarios.

cc @dprotaso

**Comment by yanweiguo** [comment]
I found this from debugging https://github.com/knative/serving/pull/9884 which enables Chaosduck for autoscaler.

**Comment by dprotaso** [comment]
There’s a bug in k8s leader election package that breaks releasing the lock
on shutdown

So on normal operation it takes a our 15-20 seconds to transition to a new
leader

**Comment by dprotaso** [comment]
Essentially the other controllers wait for the lease to expire

**Comment by dprotaso** [comment]
FYI - last week I added logging to help capture lease changes

https://github.com/knative/serving/pull/9905

Here's a program that rewrite the history so it's easier to process - https://gist.github.com/dprotaso/628b5c37b8b22ef0dfba5549d66b1fa1

Output columns are `acquireTime`, `renewTime` & `holderIdentity`, empty time values imply they're the same as row above 

```
Lease history for controller.knative.dev-serving-pkg-reconciler-serverlessservice.reconciler.09-of-10
	2020-10-22T15:25:19.999786Z - 2020-10-22T15:25:19.999786Z - controller-576d76b7cb-5xpfn_f408b22e-34d7-4844-a4aa-3f2de9d4d3ad
	                            - 2020-10-22T15:25:20.176095Z - controller-576d76b7cb-5xpfn_f408b22e-34d7-4844-a4aa-3f2de9d4d3ad
	                            - 2020-10-22T15:25:25.890993Z - controller-576d76b7cb-5xpfn_f408b22e-34d7-4844-a4aa-3f2de9d4d3ad
	                            - 2020-10-22T15:25:28.146922Z - controller-576d76b7cb-5xpfn_f408b22e-34d7-4844-a4aa-3f2de9d4d3ad
	                            - 2020-10-22T15:25:31.977282Z - controller-576d76b7cb-5xpfn_f408b22e-34d7-4844-a4aa-3f2de9d4d3ad
	                            -                             - controller-576d76b7cb-5xpfn_f408b22e-34d7-4844-a4aa-3f2de9d4d3ad
	2020-10-22T15:25:35.718546Z - 2020-10-22T15:25:35.718546Z - controller-576d76b7cb-5xpfn_f408b22e-34d7-4844-a4aa-3f2de9d4d3ad
	                            - 2020-10-22T15:25:39.091712Z - controller-576d76b7cb-5xpfn_f408b22e-34d7-4844-a4aa-3f2de9d4d3ad
	                            - 2020-10-22T15:25:42.090606Z - controller-576d76b7cb-5xpfn_f408b22e-34d7-4844-a4aa-3f2de9d4d3ad
	                            - 2020-10-22T15:25:45.033577Z - controller-576d76b7cb-5xpfn_f408b22e-34d7-4844-a4aa-3f2de9d4d3ad
	                            - 2020-10-22T15:25:48.119726Z - controller-576d76b7cb-5xpfn_f408b22e-34d7-4844-a4aa-3f2de9d4d3ad
...
	                            - 2020-10-22T15:29:59.020969Z - controller-576d76b7cb-5xpfn_f408b22e-34d7-4844-a4aa-3f2de9d4d3ad
	2020-10-22T15:30:18.777256Z - 2020-10-22T15:30:18.777256Z - controller-576d76b7cb-bnkv8_e67de3f6-1212-46dc-9550-0480ff33505a

```

**Comment by dprotaso** [comment]
I'm going to poke at k/k issues this week

**Comment by dprotaso** [comment]
Here's one bug fix: https://github.com/kubernetes/kubernetes/pull/80954 - landing in v1.20

**Comment by dprotaso** [comment]
I've cherry picked the change back to 1.19 https://github.com/kubernetes/kubernetes/pull/95926 and 1.18 https://github.com/kubernetes/kubernetes/pull/95927

**Comment by dprotaso** [comment]
Hopefully kubernetes/kubernetes#95939 lands and we can cherry pick that back to 1.18.

These changes should stabilize our leader transitions

**Comment by dprotaso** [comment]
I'm feeling hopeful that the upstream patches will come out in the next 1.18 patch release due out in 2020-11-11.

This is one day _after_ Knative's 0.19 release. So we'll probably have this fixed in a 0.19.1 release the following week

**Comment by vagababov** [comment]
Is it all in client libs or in some core component?

**Comment by dprotaso** [comment]
actually once my last PR merges we could point to a release branch SHA and switch to a formal release once it's out

**Comment by dprotaso** [comment]
k8s 1.19 cherry pick - https://github.com/kubernetes/kubernetes/pull/95963
k8s 1.18 cherry pick - https://github.com/kubernetes/kubernetes/pull/95964

**Comment by dprotaso** [comment]
re-opened since we're waiting on eventing to bump

**Comment by dprotaso** [comment]
@yanweiguo I think this should be good to close - can you re-run your tests?

**Comment by yanweiguo** [comment]
Verified it works as expected now.
