### ISSUE TITLE
Return typed (or wrapped context) error in pkg/signal.go

### ISSUE THREAD

**Issue by embano1** [knative/pkg#1854]
A pattern I see used a lot when reacting to program termination is checking for the returned error to distinct an expected, e.g. context error, from an abnormal error.

E.g.:

```go
func main() {
	ctx := signals.NewContext()
	err := run(ctx, os.Args, os.Stdout)
	if err != nil && err != context.Canceled {
		panic(err)
	}
}
```

However, this does not work as `signals` slightly deviates from the `context` behavior and returns a plain error string:

```go
// Err implements context.Context
func (scc *signalContext) Err() error {
	select {
	case _, ok := <-scc.Done():
		if !ok {
			return errors.New("received a termination signal")
		}
	default:
	}
	return nil
}
```

Proposal: either return `context.Canceled` or a wrapped error including the error message so one can assert the error, e.g. using `errors.Is(err, context.Canceled)`.

**Comment by mattmoor** [comment]
cc @dprotaso @n3wscott @markusthoemmes for thoughts

**Comment by markusthoemmes** [comment]
Absolutely, let's do it. `context.Canceled` seems fine to me.

**Comment by embano1** [comment]
Will file PR 👍
