### ISSUE TITLE
[feature] Be able to induce test failures for subresources.

### ISSUE THREAD

**Issue by vaikas** [knative/pkg#1876]
## Expected Behavior
Be able to induce failures for subresources. For example I'd like to be able to induce a failure to a patch on a subresource (say, only Status).

## Actual Behavior
Can not.

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by vaikas** [comment]
This was just an issue in documentation. Added docs and tests.
#1877

**Comment by markusthoemmes** [comment]
Done now :)
