### ISSUE TITLE
Bump k8s libs to 1.19

### ISSUE THREAD

**Issue by nak3** [knative/pkg#1881]
/area API
/area test-and-release
/kind feature

This is similar request to https://github.com/knative/pkg/issues/1280, but for v1.19.

For example, service-apis repo uses [client-go v0.19.2](https://github.com/kubernetes-sigs/service-apis/blob/3fdc5d3fb0a864d186c709f6b22d6bba088d1688/go.mod#L12) and so we hit a dependency error when using the latest service-apis in knative/networking repo.

/cc @dprotaso @mattmoor

**Comment by nak3** [comment]
Just in case, this is not urgent request for me at this moment. I am testing serving-apis but I could manage it on my local and will take some time until send/merge networking repo.

**Comment by mattmoor** [comment]
I'd have to check the schedule, but I don't think we can do this until K8s 1.20 cuts, which is after our 0.19 cuts IIUC.

Let's discuss in a little over a week?

**Comment by dprotaso** [comment]
Related: https://github.com/knative/community/issues/245#issuecomment-718316003
