### ISSUE TITLE
KubernetesMinVersionKey check doesn't work with EKS?

### ISSUE THREAD

**Issue by bobcatfish** [knative/pkg#1883]
## Expected Behavior

When the minimum version of kubernetes required is 1.15.11,  EKS 1.15 with KUBERNETES_MIN_VERSION=1.15.11 should pass the minimum version check.

## Actual Behavior

Using EKS 1.15 with KUBERNETES_MIN_VERSION=1.15.11 and Tekton Pipelines v0.16.3 raises this error:

```
kubernetes version \"1.15.11-eks-065dce\" is not compatible, need at least \"1.15.11\" (this can be overridden with the env var \"KUBERNETES_MIN_VERSION\")
```

Strangely, the Pipelines 0.16.3 docs indicate we actually need 1.16 https://github.com/tektoncd/pipeline/blob/v0.16.3/docs/install.md#before-you-begin but the error seems to indicate that the check is looking for 1.15.11 - I think the question here is whether or not the check is able to handle the string `1.15.11-eks-065dce`. If it is, then maybe we're misunderstanding the real root problem.

## Additional Info

Bug opened in Tekton: https://github.com/tektoncd/pipeline/issues/3335 

/kind bug

Not sure what area to pick!

**Comment by vagababov** [comment]
OK, so "-eks-065dce" is treated as pre release version. And pre-release versions are reverse, so no pre-release version is larger than any pre-release version. Hence `1.15.11-eks-065...` is treated as smaller than `1.15.11`.

**Comment by markusthoemmes** [comment]
ugh, yeah, we had this downstream once too. I believe requiring `1.15.11-0` does the track in that case.

**Comment by vagababov** [comment]
I've added test coverage fo the situation and a bespoke error message for the case in the liked pr.
