### ISSUE TITLE
Add `knative_revision` tags to knative provided reconcile metrics

### ISSUE THREAD

**Issue by rusde** [knative/pkg#1894]
/area monitoring

/kind feature

## Expected Behavior
Lot of controller metrics knative provides does not contains all the labels `knative_revision` [schema](https://github.com/knative/pkg/blob/master/metrics/metricskey/constants_serving.go#L43-L51) expects. Targeting following [3 metrics](https://github.com/knative/pkg/blob/master/controller/stats_reporter.go#L35-L37) in this bug

## Actual Behavior
These metrics should contain following tags which are missing when exported 
* namespace
* config
* revision
* service

For these metrics config, revision and service will be unknown. Namespace can be assigned to the namespace last object belongs to. 

In addition we should add following metric keys

* pod_name -> to avoid metric collision when HA is enabled
* resource_name -> resource that was reconciled

## Steps to Reproduce the Problem

1. Export metrics to prometheus and will not see these tags populated.

## Additional Info

None

**Comment by markusthoemmes** [comment]
Why do all metrics need to contain all these labels? Have you considered the increase in cardinality (effectively unbound) and the effects that has on memory allocation for accounting and for prometheus as a monitoring system?

**Comment by rusde** [comment]
How `knative_revision` schema is setup, it expects these tags to be present. We cannot leverage these metrics until these tags are populated. 

We already handle such cardinality data on dataplane side when request metrics has revision name tagged to it. 

I understand this might break prometheus, do you think this proposal can go ahead if this is behind a configmap flag?

**Comment by rusde** [comment]
From the PR

Is it fine if this is behind a config map setting to add these tags?

CM: https://github.com/knative/serving/blob/master/config/core/configmaps/observability.yaml#L25

Saying metrics.controller-add-knative-revision-tags

It will be turned off by default

**Comment by rusde** [comment]
Closing issue as related PR is merged
