### ISSUE TITLE
TestInformedWatcher flaky 

### ISSUE THREAD

**Issue by runzexia** [knative/pkg#1907]
/area test-and-release
/kind bug

## Expected Behavior
test always success
## Actual Behavior
test failed in https://github.com/knative/pkg/runs/1399755328,
after rerun test success
## Steps to Reproduce the Problem
not easy to reproduce, but i guess it because `informer.HasSynced` not means all EventHandler has been called

**Comment by runzexia** [comment]
failed again https://github.com/knative/pkg/runs/1401922270?check_suite_focus=true

**Comment by bobcatfish** [comment]
Hi @runzexia !! I think this might be an actual bug and we are running into this in Tekton as well, causing https://github.com/tektoncd/pipeline/issues/2815 (longer explanation in https://github.com/tektoncd/pipeline/issues/2815#issuecomment-733207368)

Looking at the assertion that's failing:

https://github.com/knative/pkg/blob/c5296cd61e9f34e183f8010a40dc866f895252b9/configmap/informed_watcher_test.go#L86-L92

It looks like the intention is that after calling `cmw.Start`, all of the callbacks have been called, but these flakes are showing that that isn't always the case (which I think makes sense b/c the callbacks are called in separate go routines).

I hacked the failing test to run in a loop and added a script to run it repeatedly in https://github.com/bobcatfish/pkg/commit/32da8032bfb04caa34dcbaea1f50b1d024bc3f44 and every time I run `doit.sh` I eventually see a failure such as:

```
+ for i in '`seq 1 1000`'
+ go test ./configmap/... -run TestInformedWatcher -count=1
--- FAIL: TestInformedWatcher (0.00s)
    --- FAIL: TestInformedWatcher/AGAIN-140 (0.00s)
        informed_watcher_test.go:94: foo1.count = 0, want 1
FAIL
FAIL	knative.dev/pkg/configmap	2.319s
```

In Tekton this means that there is a chance that when a controller starts, the values returned by the config store using this watcher might not return the right values (if the go routines that update the config store have not completed).

So I think that `InformedWatcher.Start` isn't functioning as intended and this is a bug. The fix would be to make it so that `InformedWatcher.Start` actually somehow guarantees that those callbacks have been invoked before returning, what do you think?

( @mattmoor might be relevant to your interests! )

**Comment by mattmoor** [comment]
That'd be a good find.  cc @dprotaso 

> which I think makes sense b/c the callbacks are called in separate go routines

Where do you mean?  Within the informer itself?

**Comment by bobcatfish** [comment]
> > which I think makes sense b/c the callbacks are called in separate go routines

> Where do you mean? Within the informer itself?

1. [InformedWatcher.Start](https://github.com/knative/pkg/blob/c5296cd61e9f34e183f8010a40dc866f895252b9/configmap/informed_watcher.go#L139) calls
2. [InformedWatcher.registerCallbackAndStartInformer](https://github.com/knative/pkg/blob/c5296cd61e9f34e183f8010a40dc866f895252b9/configmap/informed_watcher.go#L166) which [sets up all the event handlers](https://github.com/knative/pkg/blob/c5296cd61e9f34e183f8010a40dc866f895252b9/configmap/informed_watcher.go#L159-L162) and then calls
3. [sharedInformerFactory.Start](https://github.com/kubernetes/client-go/blob/fb61a7c88cb9f599363919a34b7c54a605455ffc/informers/factory.go#L134) which calls
4. [`go informer.Run`](https://github.com/kubernetes/client-go/blob/fb61a7c88cb9f599363919a34b7c54a605455ffc/informers/factory.go#L134) which i think **waves hands** [pops events from a queue](https://github.com/kubernetes/client-go/blob/fb61a7c88cb9f599363919a34b7c54a605455ffc/tools/cache/controller.go#L99-L105) and ultimately uses [this Process function is invoked to call the callbacks](https://github.com/kubernetes/client-go/blob/fb61a7c88cb9f599363919a34b7c54a605455ffc/tools/cache/controller.go#L393-L419) from within the goroutine ??

**Comment by mattmoor** [comment]
I would expect the wait for sync to synchronize things, if the `go` is just the `informer.Run` 🤔 

https://github.com/knative/pkg/blob/c5296cd61e9f34e183f8010a40dc866f895252b9/configmap/informed_watcher.go#L144

**Comment by runzexia** [comment]
> I would expect the wait for sync to synchronize things, if the `go` is just the `informer.Run` 🤔
> 
> https://github.com/knative/pkg/blob/c5296cd61e9f34e183f8010a40dc866f895252b9/configmap/informed_watcher.go#L144

I think `i.informer.Informer().HasSynced` would not guarantee the callback has invoked, thats the problem

**Comment by mattmoor** [comment]
That is definitely plausible, but it would be good to confirm whether the informer events are done asynchronously, and where that happens.  Just want to make sure we understand what's going on. 👍

**Comment by bobcatfish** [comment]
> would be good to confirm whether the informer events are done asynchronously, and where that happens

It _seems_ like the only place the event handlers (OnAdd, OnUpdate, OnDelete) are called is [in the Process function](https://github.com/kubernetes/client-go/blob/23fa3f5256cf5d2955fd6a65fa97b9714b7df41f/tools/cache/controller.go#L393-L420) (or by the OnUpdate function, also called ultimately in the Process function), and it seems like the Process function is only invoked via [informer.Run](https://github.com/kubernetes/client-go/blob/23fa3f5256cf5d2955fd6a65fa97b9714b7df41f/tools/cache/controller.go#L154) (via [processloop](https://github.com/kubernetes/client-go/blob/23fa3f5256cf5d2955fd6a65fa97b9714b7df41f/tools/cache/controller.go#L183)) - so I think the event handler callbacks are only invoked asynchronously? (but maybe there is some other code in play?)

**Comment by dprotaso** [comment]
> I think i.informer.Informer().HasSynced would not guarantee the callback has invoked, thats the problem

@runzexia is right.

> so I think the event handler callbacks are only invoked asynchronously

@bobcatfish is right.

**Comment by dprotaso** [comment]
Digging into the code myself `HasSynced` is true once the informers backing cache is up to date.

Notifying handlers is async and can be delayed

**Comment by bobcatfish** [comment]
Hey @dprotaso  - it looks like #1929 resolved this issue but it's only changing test code - does this mean we're okay with the potential race condition?

i.e. if you use the informedwatcher too quickly (specifically before the event handling goroutines have been invoked) you won't get the value you wanted?

Over in Tekton Pipelines where we use this to read configuration from config maps i wouldn't want to risk that we use the wrong value (however unlikely it is).

If we don't feel like InformedWatcher.Start should wait for the first sync to happen, I'd like to request that we expose some way to wait for this. Let me know if I need to open another issue.

**Comment by dprotaso** [comment]
Yeah it's not guaranteed. I guess the severity would depend - ie. sharedmain seems to wait for configmap informers first by calling Start on the watcher. Then it waits again for another set of informers that have been setup via injection.

I think it'd be hard to provide guarantees that a set of event handler were invoked. You may way to just fail reconciliation if there's some configuration that's not present but expected.

It's worth discussing so feel free to open a new issue.

**Comment by bobcatfish** [comment]
Okay @dprotaso I've opened https://github.com/knative/pkg/issues/1960 !
