### ISSUE TITLE
Enable e2e Test to capture dump queue proxy logs (off by default)

### ISSUE THREAD

**Issue by igorbelianski** [knative/pkg#1932]
## Expected Behavior
  e2e test have an on demand (env variable, flag) ability to capture / dump logs from pods in namespaces other than knative-serving.  This is particularly useful for debugging troubleshooting networking problems (namespace serving-tests to get queue-proxy logs, and potentially capture kingress logs as well)
   
## Actual Behavior
   running tests produces logs from all knative-serving pods as well as user container ()

  
## Steps to Reproduce the Problem

1. run e2e tests (go test -v -tags=e2e  ./test/e2e/...  )
2. ensure queue proxy produces logs 
    kubectl logs g-r-p-c-streaming-ping-bqasnqxe-bbsmx-deployment-968b67dfb5kq9b  -c queue-proxy  -n serving-tests
3.  observe the log entries produced by kubectl not present in the e2e log results

## Additional Info
   proposal is to  change :   
knative.dev/pkg/test/logstream/kubelogs.go  to enable it to collect logs from multiple namespaces without filtering (like it does for "chaosduck")

**Comment by igorbelianski** [comment]
@dprotaso @vagababov @markusthoemmes   
before writing this code and extendingpkg/test/logstream/v2/  to support pods across multiple namespaces and more liberal ability to disable tag filtering on some of them , i would like to get your opinion

**Comment by dprotaso** [comment]
Sounds good to me - I would only want to have the extra collection off by default since certain tests would produce a ton of extra logs. ie. auto scaling tests

**Comment by markusthoemmes** [comment]
Sounds good!
