### ISSUE TITLE
Remove --disable-ha

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#1995]
/area API
/kind cleanup

Tracking:
- [ ] net-istio is abusing defaulting webhook, which requires --disable-ha (#1979)

---

We should also cleanup references in docs etc.

Before this work is done, we should ensure nobody is still throwing this flag, but this is criteria for GAing this feature.

cc @vdemeester @lionelvillard @vaikas @yanweiguo @pmorie

**Comment by yanweiguo** [comment]
We are using this flag due to https://github.com/knative/pkg/issues/1979
