### ISSUE TITLE
Consider lowering log level for AdmissionController.Admit failures 

### ISSUE THREAD

**Issue by eddie4941** [knative/pkg#2008]
/area monitoring
/kind question

## Expected Behavior
Consider logging validation errors at a lower level (`info`) to signal that the webhook is working as expected. 

## Actual Behavior
The AdmissionController.Admit code logs validation error on CRD's with `level==error`. Validation errors are a normal function of the webhook, so logging them as `level==error` is perhaps to aggressive and misleading as the webhook is operating normally when validations fail this way.

## Additional Info
example of logging statement: https://github.com/knative/pkg/blob/6045ed499615ecca39d92a8277489de1fbe3dcff/webhook/resourcesemantics/validation/validation_admit.go#L177

**Comment by skonto** [comment]
Hi @eddie4941 if not mistaken other frameworks follow [this](https://github.com/kubernetes-sigs/controller-runtime/blob/4a8536eab22599e3af3c2cce2104e730b9c4ea65/pkg/webhook/admission/webhook.go#L142) during validation of any resource.

**Comment by dprotaso** [comment]
/reopen
/lifecycle frozen

In @skonto's example it looks like it prints the error when it fails to marshal the response.

I think failing validation shouldn't be an error because it's expected with bad input vs. something unexpected that prevents us from responding to the request.

**Comment by hzliangbin** [comment]
hi, @dprotaso
just lower the logging level to INFO and error should be return as before ?
