### ISSUE TITLE
stackdriver exporter sometimes loses metric on shutdown

### ISSUE THREAD

**Issue by quentin-cha** [knative/pkg#2011]
/area monitoring
/kind feature

## Expected Behavior
stackdriver exporter do not lose metrics when shutting down

## Actual Behavior
stackdriver exporter sometimes lose metrics when shutting down

## Additional Info
Currently during process shutdown, stackdriver exporters may lose metrics. 
This is happening because:
* Flushing isn't happening correctly, this will soon be [fixed](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/282).
* Shutdown sequence needs to be: `Stop exporter -> Wait for minimum stackdriver upload interval (~10s) -> Flush`

**Comment by skonto** [comment]
@quentin-cha what is left to be done here? I see that the fix flushes the interval reader so we need to bring the dep in, other than that what is pending the flushing part?  @evankanderson Any reason we dont flush the exporter after we replace it [here](https://github.com/knative/pkg/blob/cc278e1666caaf7c256ac823bee796e366b9ded5/metrics/exporter.go#L198)?
Currently we only flush exporters when the process is shutting down.

**Comment by quentin-cha** [comment]
Apologies for not being able to work on this. Besides pulling in the dep, we need to actually invoke `StopMetricsExporter()` before we invoke `FlushExporter()`. The complication is that export to stackdriver is rate limited to once very ~10s so in order to guarantee not losing any metrics, there should be a 10s sleep between `StopMetricsExporter()` and `FlushExporter()`

**Comment by skonto** [comment]
It affects opencensus. Should we open an issue for the retirement thing, @MontyCarter gentle ping.

**Comment by MontyCarter** [comment]
Sorry.  Not sure how I missed this.  Anyway, the stackdriver exporter can be removed.

**Comment by dprotaso** [comment]
stack driver exporter was removed
