### ISSUE TITLE
Unable to set content-type to non json/xml value

### ISSUE THREAD

**Issue by sjwoodman** [knative/pkg#203]
## Expected Behavior

In the [CloudEvent Spec](https://github.com/cloudevents/spec/blob/v0.1/spec.md#contenttype) the `ContentType` attribute is used to describe the type of the data payload of the CloudEvent. This should be able to be set to any MIME type. 

## Actual Behavior

The CloudEvents SDK gives the following error

```Failed to create http request: Cannot encode content type "text/plain"```

## Steps to Reproduce the Problem

```golang
ctx := cloudevents.EventContext{
CloudEventsVersion: cloudevents.CloudEventsVersion,
EventType:          "foo.
EventID:            "foo",
Source:             "foo",
ContentType:        "text/plain",
}
...
req, err := cloudevents.Binary.NewRequest("http://localhost:8080/foo", "foobar", *ctx)

//error
```

**Comment by odra** [comment]
Does it make sense to change this line to encode the raw data if it is neither a json or xml encoding: https://github.com/knative/pkg/blob/master/cloudevents/event.go#L175?

**Comment by evankanderson** [comment]
I believe that we are recommending https://github.com/cloudevents/sdk-go as a replacement for pkg/cloudevents at this point.

@n3wscott to confirm
/assign @n3wscott

**Comment by mattmoor** [comment]
Closing as obsolete.
