### ISSUE TITLE
How does TableTest framework trigger a delete handler function ?

### ISSUE THREAD

**Issue by zhaojizhuang** [knative/pkg#2048]
/kind question

How does `TableTest framework` trigger a `delete handler function` such as follows:

https://github.com/knative-sandbox/eventing-kafka/blob/main/pkg/source/mtadapter/controller.go#L67

## Expected Behavior

 `TableTest framework` suport trigger a delete handler funtion

## Actual Behavior

I can't find out how to trigger a `delete funtion` using  `TableTest framework`

**Comment by vagababov** [comment]
You reconcile a non-existent `key` object.

**Comment by vagababov** [comment]
Check any of the other delete tests for any of the reconcilers (service and confighave one I think).

**Comment by zhaojizhuang** [comment]
> Check any of the other delete tests for any of the reconcilers (service and confighave one I think).

ok,thanks @vagababov let me have a try
