### ISSUE TITLE
we should support k8s ingressinformer's injection 

### ISSUE THREAD

**Issue by zhaojizhuang** [knative/pkg#2067]
/kind feature

## Expected Behavior
we should support k8s ingressinformer's injection 

like #423

**Comment by markusthoemmes** [comment]
Can you elaborate on what you're after here? I don't quite understand tbh.

**Comment by zhaojizhuang** [comment]
> Can you elaborate on what you're after here? I don't quite understand tbh.

@markusthoemmes yeah, I am working on my own controller (like `sample-controller`), where I will use ingresslister, but I can't find the ingress informer.

**Comment by markusthoemmes** [comment]
If Knative itself doesn't need that informer anywhere, we shouldn't generate it in a Knative repository. You can however generate it yourself in your own repository.
