### ISSUE TITLE
Should controller framework allow users to set number of threads when processing the controller's workqueue

### ISSUE THREAD

**Issue by zhaojizhuang** [knative/pkg#2073]
/kind feature
/kind question

## Expected Behavior
Should controller framework allow users to set number of threads when processing the controller's workqueue

## Actual Behavior
we set   `DefaultThreadsPerController=2` hardcode, https://github.com/knative/pkg/blob/main/controller/controller.go#L727

**Comment by markusthoemmes** [comment]
Duplicate of https://github.com/knative/pkg/issues/1708
