### ISSUE TITLE
istio ServiceEntry missing

### ISSUE THREAD

**Issue by f4tq** [knative/pkg#208]
## Expected Behavior
- [knative/pkg/api/istio](https://github.com/knative/pkg/blob/master/apis/istio/v1alpha3/register.go#L46) does not implement [ServiceEntry](https://github.com/istio/api/blob/master/networking/v1alpha3/service_entry.proto) which is part of `apis/networking.istio.io/v1alpha3`
- Please implement it.

## Actual Behavior
- None: It is missing

## Additional Info
See [networking.istio.io/v1alpha3](https://github.com/istio/api/tree/master/networking/v1alpha3) for the full list.

**Comment by tcnghia** [comment]
/close

This is obsolete, we moved to using istio/client-go.
