### ISSUE TITLE
Injected "reconcile" can not compile when no "status" in resource

### ISSUE THREAD

**Issue by vincent-pli** [knative/pkg#2083]
## Expected Behavior
Everything works
## Actual Behavior
`pkg/client/injection/reconciler/${resource}/v1alpha1/${resource}/reconciler.go`
can not compile!
## Steps to Reproduce the Problem
My resource has no sub resource `status`, so based on the logic no `skipStatusUpdates` in `reconcilerImpl`, see the code:
https://github.com/knative/pkg/blob/5ac4a75f34884a2adc4a77ce1a6cb05cc29d897c/codegen/cmd/injection-gen/generators/reconciler_reconciler.go#L296-L300

but there is no such guard here:
https://github.com/knative/pkg/blob/5ac4a75f34884a2adc4a77ce1a6cb05cc29d897c/codegen/cmd/injection-gen/generators/reconciler_reconciler.go#L443-L447

and here:
https://github.com/knative/pkg/blob/5ac4a75f34884a2adc4a77ce1a6cb05cc29d897c/codegen/cmd/injection-gen/generators/reconciler_reconciler.go#L453-L457

it will raise compile error.
I suffered for several hours, please take a look, thanks

**Comment by vincent-pli** [comment]
@markusthoemmes 
I use https://github.com/knative-sandbox/sample-controller as template,
seems the `knative/pkg` version is:  knative.dev/pkg v0.0.0-20210331065221-952fdd90dbb0

So, you mean the issue has gone in latest version?

**Comment by markusthoemmes** [comment]
Hmm, that should easily be new enough. Can you share your code by any chance?

**Comment by vincent-pli** [comment]
@markusthoemmes 
sure, take a look this: https://github.com/vincent-pli/cel-tekton/tree/with-issue

**Comment by markusthoemmes** [comment]
Oh I see! We're indeed lacking a few more checks as you've pointed out. Sorry I misread your comments above. I guess we didn't catch that because Secrets are not KRShaped. Duh.

However, one might argue that your resource isn't KRShaped anyway (because it doesn't have a status), so you should be disabling that in the generator via the respective flag anyway.

The respective diff is

```diff
diff --git a/pkg/apis/variablestores/v1alpha1/variable_store_types.go b/pkg/apis/variablestores/v1alpha1/variable_store_types.go
index 6641d61..0e32f21 100644
--- a/pkg/apis/variablestores/v1alpha1/variable_store_types.go
+++ b/pkg/apis/variablestores/v1alpha1/variable_store_types.go
@@ -27,7 +27,7 @@ import (
 // VariableStore is a context or variables storage to help caculate the CEL expression.
 //
 // +genclient
-// +genreconciler
+// +genreconciler:krshapedlogic=false
 // +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
 type VariableStore struct {
 	metav1.TypeMeta `json:",inline"`
diff --git a/pkg/client/injection/reconciler/variablestores/v1alpha1/variablestore/reconciler.go b/pkg/client/injection/reconciler/variablestores/v1alpha1/variablestore/reconciler.go
index 58a78b7..59e9ecc 100644
--- a/pkg/client/injection/reconciler/variablestores/v1alpha1/variablestore/reconciler.go
+++ b/pkg/client/injection/reconciler/variablestores/v1alpha1/variablestore/reconciler.go
@@ -225,18 +225,10 @@ func (r *reconcilerImpl) Reconcile(ctx context.Context, key string) error {
 			return fmt.Errorf("failed to set finalizers: %w", err)
 		}
 
-		if !r.skipStatusUpdates {
-			reconciler.PreProcessReconcile(ctx, resource)
-		}
-
 		// Reconcile this copy of the resource and then write back any status
 		// updates regardless of whether the reconciliation errored out.
 		reconcileEvent = do(ctx, resource)
 
-		if !r.skipStatusUpdates {
-			reconciler.PostProcessReconcile(ctx, resource, original)
-		}
-
 	case reconciler.DoFinalizeKind:
 		// For finalizing reconcilers, if this resource being marked for deletion
 		// and reconciled cleanly (nil or normal event), remove the finalizer.
```

(the second diff is generated by update-codegen, so that should fix your issue).

I guess we might want to default `isKRShaped` to false, if `hasStatus` is false.

**Comment by vincent-pli** [comment]
Thanks @markusthoemmes 
Do we have some document, I mean some guide for adopting `knative/pkg` to avoid have to dig into code for trouble shooting?

**Comment by markusthoemmes** [comment]
Not sure we have that right now to be honest. Did the above fix your problem @vincent-pli ?

**Comment by vincent-pli** [comment]
Yes, thanks @markusthoemmes
