### ISSUE TITLE
Patterns for dealing with concurrency in Knative controllers

### ISSUE THREAD

**Issue by alan-ghelardi** [knative/pkg#2084]
I'm writing a Knative controller that creates, updates and deletes certain Github resources (e.g. hooks, keys, etc.) when a custom resource definition changes. I've been noticing race conditions that arise when two concurrent reconciliation operations are fired what leads to certain resources to get duplicated (e.g. two hooks are created). Currently, after creating a Github hook I'm saving its identifier in the resource's status to avoid calling the Github API to list existing hooks what might cause issues with rate limits or lead me to implement a complex logic to deal with pagination. So, the controller checks if the resource being reconciled has a hook ID in its status to decide if a new hook must be created or if the corresponding hook must be updated according to the current state of this resource.

Sometimes it seems that a new reconciliation flow is being triggered while the Github API is creating a new resource or before the new status is available in the shared cache, what causes the duplication. So, I was wondering whether there are known patterns in Knative to deal with this sort of concurrency in which a controller is used to reconcile an external resource whose identifier must be saved to be used later. I thought about using an external storage (such as Redis), but it seemed too intrusive or perhaps a lock based on the resource's key, but I'd like to know if Knative provides an out-the-box feature to help us to solve that problem.

**Comment by markusthoemmes** [comment]
/remove-lifecycle stale

Sorry for not answering this earlier @alan-ghelardi!

Knative's reconciler framework provides no additional tooling over concurrency control vs. reconcilers built with, for example, kubebuilder. The invariant that's kept is that a given "main" resource (the main driver of the reconcilation process) is only reconciled once at a time. The same CR should never be reconciler twice, regardless of how many threads the reconciler runs with. In general however, the reconciler can reconcile different CRs in parallel. The default worker size is 2.

We do have additional measures to allow these invariants to hold across scaling out the reconciler deployment, but it doesn't sound like that's what you're asking for.

**Comment by alan-ghelardi** [comment]
Thank you for the answer @markusthoemmes. I solved the issue by postponing update events for a few seconds (i.e. through the EnqueueAfter function) to reduce the risk of reconciling an object whose status isn't up to date yet. I'm not certainty that it's the safest solution, but it has been working so far.
