### ISSUE TITLE
dynamic informer

### ISSUE THREAD

**Issue by poy** [knative/pkg#2093]
/area API
/kind feature

## Expected Behavior
Would it be possible to add an injector for the dynamic informer?

## Actual Behavior
There is one for the dynamic client, but not the informer.

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by markusthoemmes** [comment]
I might be wrong, but isn't that what the `SharedInformerFactory` is for? It has a `ForResource` function that returns a `GenericInformer` for the passed type. The `SharedInformerFactory` is available for injection at `knative.dev/pkg/client/injection/kube/informers/factory`. Make sure to start the informers generated by `ForResource` accordingly.

**Comment by poy** [comment]
So I did try that, but I thought I had taken a wrong turn as I got the following error:

```
no informer found for xxx.yyy.zzz
```

Also, I assumed (perhaps wrongly) that `sharedmain.MainWithContext()` would start it. Is that true?

**Comment by markusthoemmes** [comment]
Probably not because you're receiving a new Informer "out of bounds" that sharedmain doesn't even know about.
