### ISSUE TITLE
EnsureLabelSelectorExpressions breaks non-Knative binding webhooks

### ISSUE THREAD

**Issue by scothis** [knative/pkg#2110]
## Expected Behavior

Knative-style bindings should work for non-knative bindings.

## Actual Behavior

I have a non-Knative, Knative-style binding that uses knative.dev/pkg/webhook/psbinding. Since https://github.com/knative/pkg/pull/1949, the mutating webhook config managed by the controller to apply the binding to is stuck in a tight update loop. The expressions in the namespace and object selector are appended for each iteration becoming longer and longer.

`EnsureLabelSelectorExpressions` has a hardcoded filter to remove expressions that include `knative.dev`, for our case, because the binding is not itself part of Knative, we use an appropriate label that does not contain `knative.dev`. While we could change that label to include `knative.dev` that would be leaking an implementation detail to end users.

The controller and webhook still functionally work, since the webhook selectors are still correct, but it is very inefficient creating high churn on the API Server and the controller manager.

## Steps to Reproduce the Problem

1. create a Knative-style binding with a define label selector that does not include `knative.dev`
2. deploy the binding
3. observe the managed mutating webhook configuration and logs to see the update loop

## Additional Info

The specific project that encountered this issue is https://github.com/vmware-labs/service-bindings

**Comment by dprotaso** [comment]
@scothis is this still an issue?

Also do you have a gist for recreating the issue - then I could probably label this a good first issue
