### ISSUE TITLE
Bump k8s libs to 1.20 or 1.21

### ISSUE THREAD

**Issue by nak3** [knative/pkg#2111]
/area API
/area test-and-release
/kind feature

This is similar request to https://github.com/knative/pkg/issues/1881, but for v1.20 or v1.21.

For example, gateway-api repo stated using client-go v0.21.0 so we hit a confliction issue as pkg still uses client-go 0.19.

/cc @dprotaso @knative/technical-oversight-committee

**Comment by dprotaso** [comment]
Something with GKE 1.19 made serving's e2e tests more flakey - so we haven't bump it yet. We've pinned serving to use 1.18 for now while we poke at what's going on

See: https://github.com/knative/serving/issues/11225

**Comment by nak3** [comment]
@dprotaso Is it ready for update?

**Comment by dprotaso** [comment]
Yup - I just need to create a 1.20 branch here: https://github.com/vdemeester/k8s-pkg-credentialprovider so serving will update cleanly
