### ISSUE TITLE
Multiple label selectors support is not be honest when creating informer factory

### ISSUE THREAD

**Issue by cdlliuy** [knative/pkg#2116]
Per discussion in https://github.com/knative/serving/pull/11142#pullrequestreview-638700574, the label selectors  on informer factory need further improvement to avoid confusions when multiple selectors  are passed through.

https://github.com/knative/pkg/blob/b558677ab03404ed118ba3e179a7438fe2d8509a/vendor/k8s.io/client-go/informers/factory.go#L80-L85,

**Comment by cdlliuy** [comment]
I would like to assign myself to fix this.

**Comment by cdlliuy** [comment]
hold on,  more discusson with Julz is on-going in https://github.com/knative/serving/pull/11142#discussion_r629087910.  I will close this if it is not valid.

**Comment by cdlliuy** [comment]
per discussion in https://github.com/knative/serving/pull/11142#discussion_r629277061,  the fix is still required to change the multiple label selector parameter to support a single selector only

**Comment by julz** [comment]
> per discussion in knative/serving#11142 (comment), the fix is still required to change the multiple label selector parameter to support a single selector only

fwiw Im fine with leaving it as multiple selectors, as long as we fix the bug so they don't potentially clobber each other
