### ISSUE TITLE
configmap.NewInformedWatcher

### ISSUE THREAD

**Issue by 2020testuser** [knative/pkg#2146]
Hi,
Could anyone please help me?
I'm still in learning phase and so any help would be greatly appreciated.

I had  configmap.NewInformedWatcher() in the code and it worked fine. I'm now using the pkg  knative.dev/pkg v0.0.0-20210602095030-0e61d6763dd6 and getting an error that  configmap.NewInformedWatcher() is unavailable.
I don't see it in the configmap package. Could anyone please let me know what is the replacement function for  configmap.NewInformedWatcher()?

Thanks in advance!

**Comment by markusthoemmes** [comment]
`NewInformedWatcher` is still available in the `configmap/informer` package, see https://github.com/knative/pkg/blob/0e61d6763dd6fffc729034423f2e2b2a02ce86ce/configmap/informer/informed_watcher.go#L49-L61

**Comment by 2020testuser** [comment]
Thanks! Was able to figure out. Ended up clearing the cache and retired. Got the packages.
