### ISSUE TITLE
Remove stack driver exporter

### ISSUE THREAD

**Issue by dprotaso** [knative/pkg#2173]
/area API
/area monitoring
/kind cleanup

@MontyCarter [gave the clear that the stack driver exporter can be removed](https://knative.slack.com/archives/CEPGNPHP1/p1624482429085800?thread_ts=1624296049.079200&cid=CEPGNPHP1)

**Comment by dprotaso** [comment]
Sent an email to the various mailing lists
knative-users - https://groups.google.com/g/knative-users/c/YEH0Y8QAaJ0
Knative-dev - https://groups.google.com/g/knative-dev/c/OAq4EJ4LEAU

**Comment by skonto** [comment]
Ok so that means we now will have opencensus and prometheus direct support only right?

**Comment by dprotaso** [comment]
@skonto yes

**Comment by dprotaso** [comment]
There hasn't been any objections so I'm going 'unhold' the PR
