### ISSUE TITLE
apis.WithinSubResourceUpdate is always clobbered

### ISSUE THREAD

**Issue by poy** [knative/pkg#2184]
/kind bug

## Expected Behavior
Webhooks skip validation during a status update.

## Actual Behavior
Webhooks still go through validation assertions during status update.

## Additional Info
While looking at https://github.com/knative/pkg/blob/4a3e56dc13b2d420e50287b254c8e6a544b3525c/webhook/resourcesemantics/validation/validation_admit.go#L140-L152

I notice that the subresource is added to the context first via `apis.WithinSubResourceUpdate`. It is then clobbered by `apis.WithinUpdate` which will overwrite it as they use the same struct as a key. I believe this implies that when the Knative webhooks invoke `apis.IsInStatusUpdate`, it will always be false.

**Comment by dprotaso** [comment]
related: https://github.com/knative/pkg/issues/2115

**Comment by dprotaso** [comment]
This is fixed
