### ISSUE TITLE
sdk/reconciler losing type information in log messages.

### ISSUE THREAD

**Issue by vaikas-google** [knative/pkg#219]
## Expected Behavior
Log messages to display what resources they are working with

## Actual Behavior
They are not:
{"level":"info","ts":1547068546.5497584,"logger":"fallback","caller":"sdk/reconciler.go:52","msg":"Reconciling &TypeMeta{Kind:,APIVersion:,} default/laconia-source"}
{"level":"warn","ts":1547068546.687146,"logger":"fallback","caller":"sdk/reconciler.go:74","msg":"Failed to reconcile &TypeMeta{Kind:,APIVersion:,}: services \"message-dumper\" is forbidden: User \"system:serviceaccount:knative-sources:gcppubsub\" cannot get services in the namespace \"default\""}
{"level":"info","ts":1547068567.1675546,"logger":"fallback","caller":"sdk/reconciler.go:52","msg":"Reconciling &TypeMeta{Kind:,APIVersion:,} default/laconia-source"}

## Steps to Reproduce the Problem

1. Run any eventing-source examples, say pubsub
2. look at the logs and you see that the type information is not properly displayed in the logs.
3.

**Comment by mattmoor** [comment]
I think this is cloud events related and obsolete?  Cc @n3wscott

**Comment by n3wscott** [comment]
/close
-Scott
