### ISSUE TITLE
Flakey test TestSpoofingClient_WaitForEndpointState/Non_matching_response_triggers_more_requests 

### ISSUE THREAD

**Issue by dprotaso** [knative/pkg#2308]
TestSpoofingClient_WaitForEndpointState/Non_matching_response_triggers_more_requests 

Details: https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_pkg/2302/pull-knative-pkg-unit-tests/1445830894286802944

**Comment by pierDipi** [comment]
This is still an issue.

/remove-lifecycle stale
