### ISSUE TITLE
Question: defining optional informers

### ISSUE THREAD

**Issue by benmoss** [knative/pkg#2309]
/kind question

## Expected Behavior
I'd like to define a controller that can work with 3rd party resources if they are installed in the cluster, but fallback to different or no behavior if they are not installed.

## Actual Behavior
Right now using sharedmain / `EnableInformersOrDie` my controller gets stuck starting informers because the types are not resolvable.

## Additional Info
https://github.com/knative/pkg/pull/2210 might be a solution, talked a little with @n3wscott about this. 

An alternate solution might be to just have a way of starting an informer but declaring that it's okay to fail, and have some way to signal that failure to the controller so it can fallback to alternate behavior.

Another solution would be to push starting informers into user-land code so you could only try to start them if some check passes (ie `if resourceInstalled { startInformer } `)

**Comment by mattmoor** [comment]
A workaround is to graph the shared informer factory and only get/start the informer if the resource is installed.

I'd rather not make the `.Get()` API any more complex than that, the point of those paths is that the dependency graph conveys what you require.  Using the injected informer factory directly seems like a reasonable way to make this optional (that's what `.Get()` uses anyways).

Does that work?

**Comment by benmoss** [comment]
> graph the shared informer factory

Not sure I understand what this would mean. Is opting out of sharedmain a baseline assumption here?

**Comment by mattmoor** [comment]
No, the webhook goes through `sharedmain` and it has a weak dependency on the secret lister here for exactly this reason: https://github.com/knative/pkg/blob/9179f78dcf97dd0990225464ee833e2446d7b4ce/webhook/webhook.go#L133-L138

If you access the informer this way, then you can make the informer optional, and guard it with some sort of environment check.  If you'd want to make it so the resulting `controller.Impl` can be nil, then you might need some small changes to `sharedmain`, but I don't think it would take much.

**Comment by benmoss** [comment]
/close

thanks! this makes sense
