### ISSUE TITLE
`version/version_test.go#L98` doesn't compile

### ISSUE THREAD

**Issue by cardil** [knative/pkg#2399]
https://github.com/knative/pkg/blob/3ba5d72e310a8cdff2663b32ac5489665ba17748/version/version_test.go#L98

Doesn't compile. Introduced in #2397.

/kind bug

**Comment by dprotaso** [comment]
We're on golang 1.17 in our CI. This is when [`t.Setenv`](https://pkg.go.dev/testing#T.Setenv) was introduced

**Comment by dprotaso** [comment]
Actually maybe we should bump the go version in go.mod as a signal

**Comment by cardil** [comment]
Exactly what I was thinking. If go1.17 is required it should be stated that way in go.mod. That's what it's for.

**Comment by dprotaso** [comment]
Oddly - maybe it didn't error because it's a test?
