### ISSUE TITLE
Invalid creator or lastModifier annotations on core resources

### ISSUE THREAD

**Issue by pierDipi** [knative/pkg#2408]
## Expected Behavior

Valid creator or lastModifier annotations are set when the group is `""` (core resources).

## Actual Behavior

The annotation is `/creator` which is invalid

## Steps to Reproduce the Problem

1. Create a webhook for a core resource
2. Run webhook

## Additional Info

/assign

**Comment by dprotaso** [comment]
for clarify core resources = https://pkg.go.dev/k8s.io/api@v0.23.3/core/v1

ie. Pods etc.
