### ISSUE TITLE
Allow overriding lease name for a reconciler

### ISSUE THREAD

**Issue by pierDipi** [knative/pkg#2411]
## Feature request

Currently, lease names are generated based on the Go
package the reconciler type is in and component name.

```
<component>.<package>.<reconciler_type_name>.<ordinal>-of-<zero_padded_num_buckets>
```

We would like to override the lease name for a particular
reconciler, in particular, this section:

```
<component>.<package>.<reconciler_type_name>
```

## Additional Info

/area API
/kind feature

**Comment by dprotaso** [comment]
Why not just configure a single bucket? using the `buckets` property?

**Comment by dprotaso** [comment]
> We would like to override the lease name for a particular reconciler, in particular, this section:

Doing this will break leader election since - you'll think you're sharing across N buckets but it's only one.

**Comment by pierDipi** [comment]
what do you mean?

I don't see how replacing from:
```
<component>.<package>.<reconciler_type_name>.<ordinal>-of-<zero_padded_num_buckets>
```
to
```
<component-y>.<package-y>.<reconciler_type_name-y>.<ordinal>-of-<zero_padded_num_buckets>
```
breaks, it works in our case.

**Comment by dprotaso** [comment]
leader election uses buckets to shard the key space which is configured here:

https://github.com/knative/pkg/blob/51be315ed160e68627a3bc51a244ec77e470c667/leaderelection/config.go#L81-L87

Each shard has a corresponding lease. If you drop the ordinal from the name then you only have a single shard which defeats the purpose of setting that bucket count

**Comment by pierDipi** [comment]
I don't what to drop the ordinal.

**Comment by pierDipi** [comment]
I want to replace the prefix `<component>.<package>.<reconciler_type_name>`.

**Comment by pierDipi** [comment]
An approach that we can have is to have a configuration in `config-leader-election` like `lease-names-prefix-remapping` that is a map from the lease prefix to a new prefix:

```yaml
lease-names-prefix-remapping: |
  <component>.<package>.<reconciler_type_name>: <new_prefix>
```

then when we instantiate the lease name we use it like this:
```go
	prefix := fmt.Sprintf("%s.%s", cc.Component, queueName)
	if v, ok := cc.LeaseNamesPrefixMapping[prefix]; ok && len(v) > 0 {
		prefix = v
	}
	return strings.ToLower(fmt.Sprintf("%s.%02d-of-%02d", prefix, ordinal, cc.Buckets))
```

what do you think?

**Comment by aliok** [comment]
The concrete usecase is that we're changing the KafkaChannel controller and we would like to use the same lease name. So, we can just deploy 2 different controller containers and once the old one is scaled to 0 the new one will be effective.

Old lease name is: `kafkachannel-controller.knative.dev.eventing-kafka.pkg.channel.consolidated.reconciler.controller.reconciler.00-of-01`

Currently, there's no way to configure the lease name, so we end up having this: `kafka-broker-controller.knative.dev.eventing-kafka-broker.control-plane.pkg.reconciler.channel.reconciler.00-of-01`

I think there was a misunderstanding about the bucket/ordinal. Bucket/ordinal is fine. The rest is not.

I think @pierDipi 's solution is simple and good. We already read the `config-leader-election` in this place anyway and it won't be adding new something expensive.

cc @dprotaso

**Comment by pierDipi** [comment]
@dprotaso can you please take a look at the proposed solution?

**Comment by dprotaso** [comment]
Thanks for the clarification I wasn't reading the issue properly.

My only question is regarding the configuration

```yaml
lease-names-prefix-remapping: |
  <component>.<package>.<reconciler_type_name>: <new_prefix>
```

Rather than embed yaml within a string an option to consider is namespacing the keys

ie. 
```yaml
loglevel.controller: "info"
loglevel.autoscaler: "info"
loglevel.queueproxy: "info"
```

So for leases you could do
```yaml
remap.<component>.<package>.<reconciler_type_name>: <new_prefix>
```

The benefit there is you can patch (add/remove) individual entries in `data` vs the entire blob.

**Comment by pierDipi** [comment]
Thanks @dprotaso ! +1

> I'm also unsure if there's a limit on the key length

I did a test, we should be good.

```yaml
apiVersion: v1
data:
  map-lease-prefix.kafka-broker-controller.knative.dev.eventing-kafka-broker.control-plane.pkg.reconciler.channel.reconciler: kafka-controller.knative.dev.eventing-kafka-broker.control-plane.pkg.reconciler.channel.reconciler
  ? map-lease-prefix.kafka-controller.knative.dev.eventing-kafka-broker.control-plane.pkg.reconciler.channel.reconciler.dakdjalfjdasjfkasjdlfkjakfdjkasjflakjdkjafkdjsalkfjdsal
  : kafka-broker-controller.knative.dev.eventing-kafka-broker.control-plane.pkg.reconciler.channel.reconciler
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-28T13:25:40Z"
  name: example
  namespace: default
  resourceVersion: "256190"
  uid: 5baa7da7-3a86-47d5-8940-9ec6093ca4a8
```
---
In case you're wondering, as I did, what `?` means in YAML, it's an alternative way of defining mappings:
```
mapping:
  ? sky
  : blue
```
It's used when executing `k get cm example -oyaml`
ref: https://yaml.org/spec/1.2.2

**Comment by pierDipi** [comment]
I have updated the PR with the suggestion from @dprotaso, please take a look https://github.com/knative/pkg/pull/2435, thanks!
