### ISSUE TITLE
Simplify the test/upgrade package

### ISSUE THREAD

**Issue by dprotaso** [knative/pkg#2421]
This whole package is really hard to review and I think part of it is because we're mixing two loggers.  Related I think we can simplify the need for this PR if we map continous tests to golang tests differently.

Take serving for example which has the following structure

```
test/upgrade.TestServingUpgrades
test/upgrade.TestServingUpgrades/InstallingBase/*
test/upgrade.TestServingUpgrades/ContinualTests
test/upgrade.TestServingUpgrades/ContinualTests/SetupProbeTest
test/upgrade.TestServingUpgrades/PreUpgradeTests/*
test/upgrade.TestServingUpgrades/UpgradeWith/*
test/upgrade.TestServingUpgrades/PostUpgradeTests/*
test/upgrade.TestServingUpgrades/DowngradeWith/*
test/upgrade.TestServingUpgrades/PostDowngradeTests/*
test/upgrade.TestServingUpgrades/VerifyContinualTests
test/upgrade.TestServingUpgrades/VerifyContinualTests/ProbeTest
```

The continous probe test is 'split' across two golang tests instances - `ContinualTests/SetupProbeTest`  & `VerifyContinualTests/ProbeTest`.  Because of this split we don't have access to a test logger during the background probing. Thus I believe that's why we have a separate logger.

The alternative would be to run the continual tests in a single `t.Run()` - then the test logger is accessible during the life of the entire 'logical' test
ie.
```
test/upgrade.TestServingUpgrades/Continual/ProbeTest
```

In this golang test instance we would run setup, the background probing and verify.

_Originally posted by @dprotaso in https://github.com/knative/pkg/pull/2293#pullrequestreview-866991548_

**Comment by dprotaso** [comment]
Hey I wasn't suggesting we flatten the entire structure - you can use `t.Parallel()` to coordinate 

Here's an example how - https://go.dev/play/p/Rzv08ipdG1D (updated to point to one with comments)

_Originally posted by @dprotaso in https://github.com/knative/pkg/issues/2293#issuecomment-1028544761_

**Comment by dprotaso** [comment]
cc @mgencur @cardil

**Comment by mgencur** [comment]
@dprotaso thanks for this. I guess this could work. I've expanded on your example and added multiple continual tests and all the other stages: https://go.dev/play/p/YNpIPxu92tF  
The test report looks nice to me. 
I can see one problem with that - if some "continual" test calls t.Fatal it will cause all continual tests to fail (including the umbrella one). When the tests call t.Error it works alright.

**Comment by cardil** [comment]
Thanks, @dprotaso, for posting this. I've seen your original message, but I had doubts about proper synchronization of those subtasks - basically the same as @mgencur checked (thanks a lot, Martin). I haven't got a chance to look at this yet.

This looks promising. I'll take a closer look at this soon. :crossed_fingers:

**Comment by cardil** [comment]
I think this might be salvageable, maybe... Two initiate problems, I found:

1. We need to start continual tests after successful installation, and pre-upgrade smoke tests, but before the upgrade starts. We need to actually wait until continual tests do their bootstrapping, before we can proceed with upgrades.
2. The current solution doesn't work well with `t.Fatal` or `t.Skip`. See: https://go.dev/play/p/JnWaE6xX7fA

**Comment by mgencur** [comment]
@cardil Yeah. the first problem can be resolved by waiting in `t.Run("Main")` until all the continual tests do their setup (possibly by using waitGroup.Wait()), before starting the upgrades. The other problem can be resolved by using this:
```
for i := 0; i < numContinualTests; i++ {
	t.Logf("Finishing %d", i)
	select {
	case done <- struct{}{}:
		// message sent
	default:
		// message dropped
	}
}
close(done)
```
When t.Fatal is called there's nobody waiting for the given signal and sending the signal to the channel blocks. The solution above could help but maybe there's even a better one.

**Comment by dprotaso** [comment]
> We need to start continual tests after successful installation, and pre-upgrade smoke tests, but before the upgrade starts. 

If that's the case just move the `t.Parallel()` call whenever you need to start the continuous tests. So in my example you could put a `t.Run("PreUpgrade")` after `t.Run("Base")`

> We need to actually wait until continual tests do their bootstrapping, before we can proceed with upgrades.

Ah good catch - yeah could use a `sync.WaitGroup` to do that extra synchronization like @mgencur suggested

ie. https://go.dev/play/p/VKql1q5K-Yu

The only thing I see that's tricky is failing the "Installation" test if setup in the "Continous" one fails. There's probably a way to massage everything into a single `t.Run` to make this easier.

I think this is easier to reason about (without wait groups): https://go.dev/play/p/5dagczP8er8

It also lets you check for failures and short circuit test execution 

> The current solution doesn't work well with t.Fatal or t.Skip. See: https://go.dev/play/p/JnWaE6xX7fA

Sending messages to the `done` channel isn't necessary - since `close(done)` effectively makes `<-done` non-blocking

so just remove this from the example
```go
for i := 0; i < numContinualTests; i++ {
	t.Logf("Finishing %d", i)
	done <- struct{}{}
}
```
