### ISSUE TITLE
For `sharedmain` zap's Fatal should deterministically calculate the POSIX return code

### ISSUE THREAD

**Issue by cardil** [knative/pkg#2495]
/area test-and-release
/kind feature

## Actual Behavior

The _Zap_'s _Fatal_ method is calling `os.Exit(1)` regardless of a message. This isn't the best _UX_ choice. The _POSIX_ return code could be used for quick assessment about a process failure. When the retcode is always equal `1` for any error, this can't be utilized.

Tools like Docker or Kubernetes report back the return code of the process. By using a deterministic algorithm to calculate the _POSIX_ return code, a quick debugging is possible. Users could indicate if the process is failing because of the same reason, without looking into logs.

## Expected Behavior

The best would be to rely on _Fatal_'s message or on an _error_ object if it's attached as a _Field_.

## Additional Info

Related to https://github.com/uber-go/zap/issues/1086

**Comment by dprotaso** [comment]
Going to close this out - see the comments on the PR. I think this will be confusing for users as certain exit codes have specific meanings.

I think the better approach would be to ensure we write to the k8s termination path

see: https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure/
