### ISSUE TITLE
Add support for AdmissionReview warnings

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#2497]
/area API
/kind feature

Kubernetes added support for [Warnings](https://kubernetes.io/blog/2020/09/03/warnings/) in the `AdmissionReview` response in Kubernetes 1.19.  The intent of this is to enable folks to give API users advance warning when a field they are using is headed towards deprecation, for instance I'd have loved to have this when we were deprecating build support in the v1alpha1 Service shape.  This also would have been very useful as we changed behaviors like disabling service links by default.

I'd suggest that we extend `apis.FieldError` to contain a "level" attribute of some sort: https://github.com/knative/pkg/blob/50410e0b833abc1a464d334b9e52e2c873dafcd4/apis/field_error.go#L31-L36

... and probably adapt the aggregated internal storage `errors []FieldError` to something more like `diagnostics map[string]FieldError` (this is private, so it should be safe).

In the webhook where we consume this: https://github.com/knative/pkg/blob/50410e0b833abc1a464d334b9e52e2c873dafcd4/webhook/resourcesemantics/validation/validation_admit.go#L81-L83

... we would then add some sensitivity to this new functionality.

---

I believe that the Tekton folks will find this interesting as they head towards things like PipelineResources deprecation and v1 (cc @vdemeester @bobcatfish @imjasonh @afrittoli )

I believe that the `cosigned` folks will find this interesting as a mechanism for surfacing a "Warn" mode on ClusterImagePolicy resources (cc @vaikas @hectorj2f).  I think this would give @vpnachev a solid path for what he wants in https://github.com/knative/pkg/issues/2494

I also think this would have (and will be) enormously useful for surfacing diagnostics to users in Knative itself! (cc @dprotaso )

---

I'd be happy to throw together a change with the picture forming in my head for this, if that's help illustrate things for folks.

**Comment by hectorj2f** [comment]
+1 🙂

**Comment by vaikas** [comment]
Yeah, when I saw that warning mode, was mosdef thinking that would be warning for cosigned webhooks mode for policies failing instead of trying, seems like they described our use case to a T :)

```
webhook implementations adding a "complain" mode, where they return warnings instead of rejections, to allow trying out a policy to verify it is working as expected before starting to enforce it
```

**Comment by mattmoor** [comment]
Ok, I threw together the linked PR: https://github.com/knative/pkg/pull/2498

It has a `/hold` on it for now, so it doesn't merge before we can get a bunch of 👀 on it, but I'm pretty excited at the possibilities this enables!  In particular, I threw a TODO in one place that popped out around our "deprecated field" handling logic, which I think could ~immediately take advantage of this.

**Comment by hectorj2f** [comment]
Thanks @mattmoor
