### ISSUE TITLE
Tekton downstream tests fail consistently

### ISSUE THREAD

**Issue by imjasonh** [knative/pkg#2499]
Seems to be two distinct issues (so far...)

1. for tektoncd/chains, [`use of internal package github.com/hashicorp/go-plugin/internal/plugin not allowed`](https://github.com/knative/pkg/runs/5855970652?check_suite_focus=true)
    - seemingly introduced in https://github.com/knative/pkg/pull/2481 when bumping the Go version from 1.16 -> 1.17 :thinking:
    - I'm unable to reproduce this locally with Go 1.17 or 1.18...
1. for tektoncd/triggers, [`unknown field 'Handler' in struct literal of type "k8s.io/api/core/v1".Probe`](https://github.com/knative/pkg/runs/5855970695?check_suite_focus=true)
    - seemingly caused by triggers being on an older k8s version (0.22.5) than knative/pkg (0.23.5), and there being a Go-API breaking change in the interim, renaming `Handler` to `ProbeHandler`
    - hoping https://github.com/tektoncd/triggers/pull/1351 fixes 🤞 

/kind bug
/assign @imjasonh
cc @dprotaso

**Comment by dprotaso** [comment]
Last thing is https://github.com/tektoncd/chains/issues/426#issuecomment-1115558265

**Comment by dprotaso** [comment]
looks like it's green
