### ISSUE TITLE
Deprecate pool in favor of errgroup?

### ISSUE THREAD

**Issue by imjasonh** [knative/pkg#2556]
AIUI, [`pkg/pool`](https://pkg.go.dev/knative.dev/pkg/pool) has nearly the same interface and use case as [`errgroup`](https://pkg.go.dev/golang.org/x/sync/errgroup):
- run some functions in parallel using goroutines
- stop and return an error when any goroutine fails
- take a `context.Context` so the whole group can be stopped if the context is cancelled
- be able to limit concurrency (typically to `runtime.NumCPU`)

It might have been that `pool` provided more functionality than `errgroup` at one point in time, but with `errgroup` getting `SetLimit` [recently](https://go-review.googlesource.com/c/sync/+/405174), I don't think that's the case anymore.

Maintaining this code yourself is an option, but concurrency can get tricky, and if possible it'd probably be worth making it someone else's problem. Future performance improvements may get made to `errgroup` which we could just pick up.

As far as external users, cosign depends on pkg/pool, until https://github.com/sigstore/cosign/pull/2092, and it looks like mink uses it too, but I can send a PR for that too.

/kind question
/area API

btw if this sounds good I'm happy to do the work to migrate knative's own usages, and help anybody else using it to migrate.

**Comment by dprotaso** [comment]
Let's drop the uses here:
https://pkg.go.dev/knative.dev/pkg/pool?tab=importedby

and just delete this package

**Comment by dprotaso** [comment]
`errgroup` getting `SetLimit` is great
