### ISSUE TITLE
Warnings are silently dropped by k8s due to newlines.

### ISSUE THREAD

**Issue by vaikas** [knative/pkg#2581]
/kind bug

## Expected Behavior
When creating a warning like this:

```
warnField := apis.ErrGeneric(fmt.Sprintf("failed policy: %s", failingPolicy), "image").ViaFieldIndex(field, i)
warnField.Details = warnDetails
errs = errs.Also(warnField).At(apis.WarningLevel)
```
I would expect this to work. However, this turns into something like this:
```
{
	"kind": "AdmissionReview",
	"apiVersion": "admission.k8s.io/v1",
	"response": {
		"uid": "f3ebec5c-6302-4efb-9ef8-49215353a566",
		"allowed": true,
		"warnings": ["failed policy: image-policy-keyless: spec.containers[0].image\nregistry.local:5000/sigstore/demo@sha256:a420f0e3a1f8c20c6be3caaca3d6601139806b7dc5d7e4256a912675cfd319c6 signature keyless validation failed for authority authority-0 for registry.local:5000/sigstore/demo@sha256:a420f0e3a1f8c20c6be3caaca3d6601139806b7dc5d7e4256a912675cfd319c6: Get \"https://registry.local:5000/v2/\": dial tcp: lookup registry.local on 10.12.0.10:53: no such host; Get \"http://registry.local:5000/v2/\": dial tcp: lookup registry.local on 10.12.0.10:53: no such host"]
	}
}
```
Note the `\n` that we use to construct the error message by joining on `\n`

I'd argue this is not very well spelled out here what's allowed and not allowed:
https://github.com/kubernetes/api/blob/master/admission/v1/types.go#L144

But, digging deeper, the the problem is that k8s silently ignores this:
https://github.com/kubernetes/apiserver/blob/b10345148a460f9ed3dc576871a547953d021adf/pkg/endpoints/filters/warning_test.go#L83-L85

I would expect warnings to get created by our pkg to get wired through to `kubectl` properly.

## Actual Behavior
The warning message gets dropped on the floor, and nothing is passed to `kubectl`.

## Steps to Reproduce the Problem

1.  Create the warning like above that includes `details`, or anything that causes a `join` to happen.
2. 
3.

## Additional Info
Thanks @mattmoor for second set of eyes for digging into this :)

**Comment by vaikas** [comment]
The place where filtering happens is here:
https://github.com/kubernetes/apimachinery/blob/master/pkg/util/net/http.go#L661

And, you can see that having a `\n` will flag this as having runes, thereby returning error (that's silently ignored by the links above). I put this small sample to demo it:
https://go.dev/play/p/J8PbCrPcHES

So if we were to join Warnings with `\\n` it would at least go through this check, but I'll play with it to see how that even looks like...

**Comment by mattmoor** [comment]
Thanks so much for tracking this down @vaikas 

A few options to throw out instead of escaping:
 - `strings.Split` on newline and use multiple `Warnings` -- this is the most safe to users adding `\n` in the middle of an error (in addition to how we do `Details`).
 - Hide `Details` from the stringified `Warnings` -- I know we're using this currently, plus it only fixes one piece.

If we go the escaping route, we should escape all the control characters...

**Comment by vaikas** [comment]
Good points, started looking at strings.Split also because the escaping looked goofy :)
