### ISSUE TITLE
Common e2e/conformance infrastructure

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#26]
This repo houses shared Knative libraries.  The original intent was to share common controller libraries and whatnot, but I think that there's a clear and growing need to share common test and release logic as well.

Two clear candidates off the top of my head (the common bits):
1. `github.com/knative/serving/pkg/controller/testing`
1. `github.com/knative/serving/test`

cc @bobcatfish (emeritus)

**Comment by srinivashegde86** [comment]
All the common things have been moved to pkg/.

**Comment by bbrowning** [comment]
Looking in each repo's test folder, we can probably still reduce copy/paste across e2e test setups in every repo. The files under the `test/` folders like `cleanup.go`, `clients.go`, `crd.go`, `crd_checks.go`, `states.go`, and perhaps more. They aren't identical in every repo but there is a good bit of overlap.

**Comment by srinivashegde86** [comment]
The PR you just linked has some commonalities between eventing and serving repos. We did not want to keep serving specific methods in pkg/test/.

That said, I can see a few methods that can be moved to pkg that talk to k8s or istio

**Comment by srinivashegde86** [comment]
This was originally used for creating a common pkg/test package, which is done. If we need new ones, lets open new issues to track them. 

/close
