### ISSUE TITLE
Downstream Tekton failures

### ISSUE THREAD

**Issue by imjasonh** [knative/pkg#2643]
https://github.com/knative/pkg/actions/runs/3523153290/jobs/5906969056
tektoncd/pipeline fails with:

```
Building with tags: conformance,e2e,examples,linux,tools,windows,windows_e2e
Error: vendor/github.com/Microsoft/go-winio/tools.go:5:8: import "golang.org/x/tools/cmd/stringer" is a program, not an importable package
Error: hack/tools.go:20:2: import "github.com/ahmetb/gen-crd-api-reference-docs" is a program, not an importable package
Error: hack/tools.go:8:2: import "github.com/tektoncd/plumbing/cmd/combine" is a program, not an importable package
Error: hack/tools.go:11:2: import "k8s.io/code-generator/cmd/client-gen" is a program, not an importable package
Error: hack/tools.go:12:2: import "k8s.io/code-generator/cmd/deepcopy-gen" is a program, not an importable package
Error: hack/tools.go:13:2: import "k8s.io/code-generator/cmd/defaulter-gen" is a program, not an importable package
Error: hack/tools.go:14:2: import "k8s.io/code-generator/cmd/informer-gen" is a program, not an importable package
Error: hack/tools.go:15:2: import "k8s.io/code-generator/cmd/lister-gen" is a program, not an importable package
Error: hack/tools.go:16:2: import "k8s.io/kube-openapi/cmd/openapi-gen" is a program, not an importable package
Error: hack/tools.go:18:2: import "knative.dev/pkg/codegen/cmd/injection-gen" is a program, not an importable package
```

This one at least is seemingly related to go_ls_tags detecting that it should build with `tools` -- and `linux` and `windows`, which also won't work. Is `go-ls-tags` supposed to print the list of all build tags, so that we can `go build` with _all_ of them?

---

https://github.com/knative/pkg/actions/runs/3523153290/jobs/5906969257
tektoncd/chains fails with:

```
Building with tags: e2e
package github.com/tektoncd/chains/third_party/github.com/hashicorp/go-plugin
Error: 	third_party/github.com/hashicorp/go-plugin/grpc_broker.go:14:2: use of internal package github.com/hashicorp/go-plugin/internal/plugin not allowed
```

This one might be caused by `go build ./...` which includes third_party mirrored code not intended to be built this way.

---

https://github.com/knative/pkg/actions/runs/3523153290/jobs/5906969362
tektoncd/triggers fails with:

```
Error: cannot list tags: indexing failed: 
 - bufio.Scanner: token too longexit status 35
```

This one I don't know. Maybe `go-ls-tags` is barfing on a line that's too long?

---

I'm not sure what we should do about these. I'm sort of inclined to stop bothering to test this if debugging the tests is going to require this much care and feeding.

cc @dprotaso @cardil @vdemeester 

/area test-and-release
/kind bug

**Comment by imjasonh** [comment]
Yeah, it looks like the downstream test is trying to `go build ./... -tags=$(all,the,tags)`, which simply isn't how Go build tags are intended to be used, in Tekton at least.

```
tags="$(go run knative.dev/test-infra/tools/go-ls-tags@latest --joiner=,)"
echo "Building with tags: ${tags}"
go test -vet=off -tags "${tags}" -exec echo ./...
```

https://github.com/knative/actions/blob/2e26a6721fc7513123dc423dbabcf75a62d85a48/go/downstream-test/action.yaml#L44-L47

`go test -exec echo` seems to be a trick to get `go build` to include all test programs. In any case, `-tags` aren't meant to all be applied at once like this.

**Comment by dprotaso** [comment]
Action issue: https://github.com/knative/actions/issues/86

**Comment by cardil** [comment]
Here's a PR to fix this https://github.com/tektoncd/pipeline/pull/5783
