### ISSUE TITLE
Feature: Generic admission webhook

### ISSUE THREAD

**Issue by lbernick** [knative/pkg#2644]
/area API
/kind feature

We use the defaulting and validating admission webhook helpers downstream in Tekton and they are super useful. It would be nice to have a function for a generic admission webhook that takes care of certificates and reconciliation, but exposes the function `func (ac *reconciler) Admit(ctx context.Context, request *admissionv1.AdmissionRequest) (resp *admissionv1.AdmissionResponse)`. 

I'm trying to patch a CRD on creation, and have currently [implemented this as a callback passed to `defaulting.NewAdmissionController`](https://github.com/tektoncd/experimental/blob/f9d90fdd74e08127bcc7feb107fa780281b2ca80/concurrency/cmd/webhook/main.go#L36-L62), but I realized the CRD namespace is not necessarily available in the [unstructured object](https://github.com/knative/pkg/blob/f5c1a03ab4f1efa8642fc7021960c1b86da5613f/webhook/resourcesemantics/defaulting/defaulting.go#L268-L269) created from `AdmissionRequest.Object` and `AdmissionRequest.OldObject`, so I'm hoping to get this info from [AdmissionRequest.Namespace](https://pkg.go.dev/k8s.io/api/admission/v1#AdmissionRequest).

I also want to avoid [calling `SetDefaults`](https://github.com/knative/pkg/blob/f5c1a03ab4f1efa8642fc7021960c1b86da5613f/webhook/resourcesemantics/defaulting/defaulting.go#L349).

If this feature is of interest I can give implementing it a try.

**Comment by dprotaso** [comment]
Related: https://github.com/knative/pkg/issues/2656

I think having access the the `AdmissionRequest` on the `context` would help

**Comment by wlynch** [comment]
@lbernick UserInfo should be available via [apis.GetUserInfo](https://pkg.go.dev/knative.dev/pkg@v0.0.0-20230829134737-fcccb4e1a0a4/apis#GetUserInfo)! 😎
