### ISSUE TITLE
Identical version referenced in status.ConvertTo

### ISSUE THREAD

**Issue by JeromeJu** [knative/pkg#2655]
The conversion from [duckv1beta1.Status](https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1beta1/taskrun_types.go#L136) to [duckv1.Status](https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1/taskrun_types.go#L124) is not provided in the knative package. Instead  [ConvertTo](https://github.com/tektoncd/pipeline/blob/main/vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go#L109) which converts the STATUS to the same apiVersion (*v1beta1.status ConvertTo *v1beta1.status). Is this made on purpose or we shall have a convertTo function for v1beta1 to v1?

## Expected Behavior
ConvertTo for duckv1beta1 `status_types` should be converting to duckv1

## Actual Behavior
ConvertTo for duckv1beta1 `status_types` is converting to duckv1beta1

## Additional Info
Referenced in https://github.com/tektoncd/pipeline/pull/5794#discussion_r1031827225

**Comment by dprotaso** [comment]
cc @vaikas for input

**Comment by dprotaso** [comment]
fwiw - v1beta1.Status and v1.Status are identical and you can probably just change the go type in your API

**Comment by JeromeJu** [comment]
Thanks for the answer @dprotaso! 
Could you help me understand by `changing the go type` does it mean changing the API field identical for both `v1beta1` and `v1` version? But what seems happen here in our api we essentially want `duckv1` for our `v1` version and `duckv1beta1` for `v1beta1`. Can I learn from you if there is a work around with that?

**Comment by vdemeester** [comment]
@JeromeJu The are identical but not aliased. This probably means that we can refer to `duckv1` in all our types (`v1beta1` and `v1` for `tekton.dev`) and it would just work. Given that it's a `v1` as well, I don't think there is any risk of it changing drastically 👼🏼

**Comment by JeromeJu** [comment]
Thanks @dprotaso for answering. Closing this as found out the `ConvertTo` is not implementing the conversion for `v1beta1` to `v1`.
