### ISSUE TITLE
Drop dynamic wrapped client generation

### ISSUE THREAD

**Issue by dprotaso** [knative/pkg#2739]
/assign @dprotaso 

We have lots of code generation to support using a dynamic client driving a typed kubernetes interface. This was introduced in https://github.com/knative/pkg/pull/2210 It's not clear if this is really being used anywhere.

What we do know is 
- it's not fully implemented (bunch of panics in the code)
- it causes friction when updating k8s deps
- it prevents downstream implementations from bumping their k8s version to a higher one 
 -- https://github.com/knative/pkg/issues/2725

I propose we drop this logic from `knative/pkg`

The only use of the dynamic injection  I found was https://github.com/tektoncd/triggers/pull/1207 but they don't seem to use the wrapped clients

**Comment by dprotaso** [comment]
cc @mattmoor in case you have more references to usages

**Comment by mattmoor** [comment]
We use this downstream to inject clients that exhibit different behavior.

cc @wlynch who I know spent a bunch of time looking at improving things a few weeks ago to streamline updates.

**Comment by dprotaso** [comment]
> exhibit different behavior.

In what way?

> We use this downstream...

I'm thinking of making the generation optional - so you can just generate these yourself downstream

**Comment by mattmoor** [comment]
@dprotaso I think for downstream codegen to work, the clients would need to be in their own go module, so that folks can `go mod -replace` with additional options.

**Comment by dprotaso** [comment]
I don't understand. I'm suggesting downstream add a generation script like so

https://github.com/knative/pkg/blob/db8a35330281c41c7e8e90df6059c23a36af0643/hack/update-codegen.sh#L46-L54

But add a flag `--force-dynamic-clients` or something to get the extra dynamic stuff

**Comment by dprotaso** [comment]
So looking at all the downstream packages that depend on `injection.Dynamic` I only see registration of dynamic clients and informers (due to codegen/cargo culting with no actual use). 

The only downstream dependency that seems to setup the context with a dynamic client is tekton triggers

```go
cache/github.com/tektoncd/triggers@v0.24.0/cmd/eventlistenersink/main.go:	ctx = injection.Dynamic.SetupDynamic(ctx)
```

But then they setup the `Default` Informers and clients overriding everything. _So `injection.Dynamic` doesn't really have any usage._

Also based on https://github.com/knative/pkg/pull/2210 

> One of the long-standing motivations for the injection-based controller architecture has been to enable us to synthesize different backing implementations, which can be made available to controller constructors by substituting what foo.Get(ctx) accesses.

I agree with this statement but I would envision the implementation to just use the same object graph as `injection.Default` vs. a separate one

ie. I would setup things this way

```go
import "context"
import "k8s.io/client-go/dynamic"
import "knative.dev/pkg/client/injection/kube/client"
import "knative.dev/pkg/injection/clients/dynamicclient"

func main() {
  ctx := context.Background()
  dc := dynamic.NewForConfigOrDie(cfg)

 ctx = context.WithValue(ctx, dynamicclient.Key{}, dynamic.NewForConfigOrDie(cfg))
 ctx = context.WithValue(ctx, client.Key{}, myOwnKubernetesWrapper{dc})
}

type myOwnKubernetesWrapper struct {
   dc *dynamic.Client
}

var _ kubernetes.Interface = (*myOwnKubernetesWrapper)(nil)
```

Based on all this I'm inclined to delete the wrapped client, the informers, and `injection.Dynamic` - it should be fairly trivial to just remove registrations downstream (via codegen)

**Comment by pierDipi** [comment]
Thanks for the assessment @dprotaso !

**Comment by vdemeester** [comment]
Arf, this was used in `tektoncd/pipeline` 😅
