### ISSUE TITLE
Make Knative Health Ports Configureable 

### ISSUE THREAD

**Issue by engedaam** [knative/pkg#2765]
## Expected Behavior
The health port should be configureable. https://github.com/knative/pkg/blob/7051d301e7f40b15ae9c37ebdf1d36051d326eb1/injection/sharedmain/main.go#L319

## Actual Behavior
Our team would like to utilize the knative health port, but we are limited to port 8080, and wanted to the port to be configurable

**Comment by dprotaso** [comment]
Hey - do you have context on why you are limited to port 8080?
