### ISSUE TITLE
Add `Audience` field in `duckv1.Addressable`

### ISSUE THREAD

**Issue by creydr** [knative/pkg#2795]
To allow Addressables to provide their Audience field, the `duckv1.Addressable` needs to be extended to include the `Audience`:

```
type Addressable struct {
    
    ...

	// Audience is the OIDC audience for this address.
	// +optional
	Audience *string `json:"audience,omitempty"`
}

```

**Time Estimate (optional)**

1 

**Additional context (optional)**

/good-first-issue

**Comment by abhijeetgauravm** [comment]
Can u assign me?

**Comment by creydr** [comment]
> Can u assign me?

/assign @abhijeetgauravm 

You can do this too by using `/assign`. You can also find the list of prow commands here: https://prow.knative.dev/command-help

**Comment by abhijeetgauravm** [comment]
> > Can u assign me?
> 
> /assign @abhijeetgauravm
> 
> You can do this too by using `/assign`. You can also find the list of prow commands here: https://prow.knative.dev/command-help

okay sure @creydr
