### ISSUE TITLE
Drop mako code and dependency

### ISSUE THREAD

**Issue by ReToCode** [knative/pkg#2820]
We removed the dependency to [mako](https://github.com/google/mako) from Serving in https://github.com/knative/serving/pull/14289.

With this no longer used, the mako go depencendy and all the stub code here in `pkg` can be dropped.

**Work needed**
- Check for usage of mako in all knative and knative-extensions repositories prior to deleting it here
- Drop mako golang dependency
- Drop code at "knative.dev/pkg/test/mako/stub-sidecar"
- Find other references (if any) and drop them as well

**Comment by ReToCode** [comment]
Eventing still has a dependency on the mako-stub. So this task is on hold, until this dependency is removed.

**Comment by dprotaso** [comment]
cc @pierDipi do you plan on continuing using this stub?

**Comment by pierDipi** [comment]
I'm not aware of anybody using the performance tests in Eventing, I believe we can remove them and with that the mako usage

**Comment by pierDipi** [comment]
https://github.com/knative/eventing/pull/7707
