### ISSUE TITLE
Set up prow

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#3]

**Comment by adrcunha** [comment]
I sent Prow config PR for review.

@mattmoor please make sure that Serving Robots is an admin of this repo for Prow to work.

**Comment by mattmoor** [comment]
@adrcunha thanks, I added "Serving Robots" (we should rename to "Knative Robots")

IDK if I can add "tide" until the first time it runs, at which point I'll add it.

**Comment by adrcunha** [comment]
@mattmoor I forced tide to appear in the checks in https://github.com/knative/pkg/pull/14
You should be able to enforce it now in the setting.

**Comment by mattmoor** [comment]
Thanks, done.

We still need unit testing and coverage.  LMK if I can do this myself and where :)

**Comment by adrcunha** [comment]
https://github.com/knative/pkg/pull/18 sets up the basics for those. Once it's in I can set up the jobs.

**Comment by adrcunha** [comment]
@mattmoor now the test jobs can be marked as required checks, see https://github.com/knative/pkg/pull/14

**Comment by mattmoor** [comment]
/area test-and release

Done for everything except coverage (though I think only tide matters?)

**Comment by adrcunha** [comment]
That's correct.
