### ISSUE TITLE
Stop using global variables in favor of context.

### ISSUE THREAD

**Issue by RafaeLeal** [knative/pkg#3045]
Hello! I'm trying to write an integration test between two projects that use knative.dev/pkg for building reconcilers.
Generally, it's working fine, but I'm facing a problem because I need to start two "sharedmain" projects, one for each one, 
and they use different namespaces/configuration. The problem is that when we use static info like `system.Namespace()` it makes really hard to compose such runtime. 

So I guess my question is: would it be welcome changes to stop using global variables in favor of `context.Context`? We can make it backward-compatible by automatically adding default values into the context when not found.

**Comment by dprotaso** [comment]
> start two "sharedmain"

That's not really how the package is meant to be consumed. If you need to run different controllers in the same process you would just use a single sharedmain and merge the list of controllers.

**Comment by dprotaso** [comment]
> would it be welcome changes to stop using global variables in favor of context.Context? 

At this point I don't think we would want to introduce such a change - the use of the `system.Namespace()` and some other functions are fundamental assumptions at this point. Even in tests.

**Comment by RafaeLeal** [comment]
> That's not really how the package is meant to be consumed. If you need to run different controllers in the same process you would just use a single sharedmain and merge the list of controllers.

Even if I use a single sharedmain, I still can't run controllers in multiple namespaces.. and the only limitation here is the fact that we are using an env var, which it's not thread safe to update.

> At this point I don't think we would want to introduce such a change - the use of the system.Namespace() and some other functions are fundamental assumptions at this point. Even in tests.

I've checked, and most (if not all) functions that use `system.Namespace()` already receives context.Context. In terms of tests, it would help tests, since you wouldn't require a `os.Setenv(system.NamespaceEnvKey, "knative-testing")` anymore. And would enable to test the integration of controllers running in different namespaces.

**Comment by dprotaso** [comment]
Yeah I understand you needs. I don't think we'd want to make the changes to accommodate this. 

As a workaround you could launch your different controllers in two child processes.

**Comment by dprotaso** [comment]
Here's an example on how to launch these processes in a golang test

https://go.dev/talks/2014/testing.slide#23

**Comment by dprotaso** [comment]
Going to close this out - thanks for reaching out prior.
