### ISSUE TITLE
Configmap for defaults

### ISSUE THREAD

**Issue by josephburnett** [knative/pkg#306]
## Expected Behavior

I would like to be able to use a config map when setting defaults in the webhook.

## Actual Behavior

However, because the webhook is common and abstracted, I cannot construct one and get it through to the defaulting function.  E.g. I would like to pass in a config map watcher [here](https://github.com/knative/serving/blob/4c08227dbdb5145622ad4d246cfcacae86c5bdf9/cmd/webhook/main.go#L106) and have that config map passed to the `SetDefaults` function [here](https://github.com/knative/serving/blob/4c08227dbdb5145622ad4d246cfcacae86c5bdf9/pkg/apis/autoscaling/v1alpha1/pa_defaults.go#L24).

## Additional Info

I used a package scoped var to work around this limitation in https://github.com/knative/serving/pull/3103.

**Comment by mattmoor** [comment]
I think what I'd like to see here is changing these interfaces to pass a `context.Context` argument, and using the work by @dprotaso to attach some of these configs to it.
