### ISSUE TITLE
All-zero port listening exists in weebhook,  add configurable parameters host ip？

### ISSUE THREAD

**Issue by wenbinyang** [knative/pkg#3086]
## Expected Behavior
![image](https://github.com/user-attachments/assets/4087c3fa-2bb8-4e68-b63e-d955c4d350e7)

## Actual Behavior
![image](https://github.com/user-attachments/assets/e23aa30e-7e80-4fab-97e0-ff985d48beb0)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by dprotaso** [comment]
The webhooks typically run in a container so binding to all IPs is fine. What's issue is this causing you?
