### ISSUE TITLE
Start using semver for PKG

### ISSUE THREAD

**Issue by n3wscott** [knative/pkg#326]
It is crazy hard to integrate with pkg changes that are api breaking.

**Comment by coryrc** [comment]
Is this really possible given how tightly coupled the repos are with pkg?
Should we not be updating pkg vendoring in repos daily?

**Comment by Cynocracy** [comment]
https://docs.google.com/document/d/1fkZOpl6X9JcHRsYT3VLQI2F4xVSBmwPh16XMSakfgm4/edit#

**Comment by Cynocracy** [comment]
I have a proposal for this, I think we should do it.

**Comment by Cynocracy** [comment]
Which is to say, I would love to hear folks thoughts on the proposal, I think that semvers would be very beneficial and can be done in a lightweight way.
