### ISSUE TITLE
verify codegen not running/working for knative/pkg

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#354]
In [this PR](https://github.com/knative/pkg/pull/352/files) I see files being codegen'd (`testing/zz_...`) that should have been codegen'd before the associated change was submitted.

**Comment by evankanderson** [comment]
/assign @trshafer 

Thomas updated `gengo` but apparently wasn't required to run update-codegen.

**Comment by trshafer** [comment]
@mattmorr #353 adds the verification script to this repo.
