### ISSUE TITLE
PortForwarder function does not work with kubernetes.Clientset

### ISSUE THREAD

**Issue by dubee** [knative/pkg#388]
The `PortForwarder` function in the monitoring package does not work unless Kubernetes configuration is exported via the `KUBECONFIG` environment variable. Since the `GetPods` function in the same package works with `kubernetes.Clientset`, I expected `PortForwarder`  to work the same way.

Link to `PortForwarder`  function: 
https://github.com/knative/pkg/blob/master/test/monitoring/monitoring.go#L62

**Comment by vagababov** [comment]
I don't think that you can port-forward using kube client...

**Comment by mattmoor** [comment]
I'm puzzled about the motivation here.  What's the use case?  cc @mdemirhan
