### ISSUE TITLE
Extend Addressable

### ISSUE THREAD

**Issue by akashrv** [knative/pkg#395]
Today, Addressable struct is defined as 
```
type Addressable struct {
	Hostname string `json:"hostname,omitempty"`		
}
```
[Addressable interface](https://github.com/knative/eventing/blob/master/docs/spec/interfaces.md) is defined as 

> An Addressable resource receives events over a network transport (currently only HTTP is supported). The Addressable returns success when it has successfully handled the event (for example, by committing it to stable storage). When used as an Addressable, only the acknowledgement or return code is used to determine whether the event was handled successfully. One example of an Addressable is a Channel.

In its current definition, Addressable imposes certain limitations.

1. http scheme is implied and not other scheme is supported.
2. Even for http scheme, detailed http URL address cannot be specified such as ports, path etc.
3. Only one address could be specified by an addressable.

These limitations have been noticed in multiple use cases.
1. Channel dispatchers would like requests from different Channels to be routed to same dispatcher service. However, the dispatcher service needs to disambiguate requests coming from different channels. Doing this with just HostHeader requires dispatchers to create ExternalName services or multiple K8s services and then maintain a map of which service points to which channel. This could be simplified by using 'url path' as is used by Triggers.
2. Serving has a a type that requires an internal and an external address. @mattmoor  to add more details about this one.

Related issues: 
- [Add support for a urlPath to Sinks](https://github.com/knative/eventing-sources/issues/325)
- [Extend addressable with URL](https://github.com/knative/pkg/pull/362)

Proposal: Just based on above limitations here is a probable proposal
```
type Addressable struct {
         addresses map[string]*apis.URLRef `json:"url,omitempty"`
}
```
- Addressable would have list of named addresses, where
  - key to the map is the name of the address
  - value is a URLRef. URLRef will be new type that will enable URLs to be represented as strings on wire but in code it will be parsed into a url.URL. Refer to https://github.com/knative/pkg/pull/362/files for more details.
- a URL (scheme:[//authority]path[?query][#fragment]), where authority = [userinfo@]host[:port] keeps the design open-ended to support different schemes in Knative in future.
- We can have the "default" key reserved as the default URL or can add another field that will be a mandatory default URL, while the map is optional.

Above list of limitation, use cases and the proposal is just to kick off the discussion. The goal of this proposal is to capture all such requirements and come-up with a proposal that could be implemented with 'beta' Knative apis.

Please feel free to add your thoughts or extend the list of limitation and requirements in comments.

**We would like to close this preferably in 0.6 release.**

**Comment by mattmoor** [comment]
I am fine with the URL as the value (but I don't understand `*apis.URLRef`?  This needs to be a string.).

I am concerned about having a map here; in particular the ambiguous keyspace a map affords is dangerous to the point of potentially defeating the purpose of us introducing this duck type in the first place.  Duck typing is about having a common partial schema, and unless that extends to the keyspace here, it becomes challenging to take advantage of.  Moreover, if the keyspace is restricted then there is little advantage to a map vs. fields.  If this is here to just accommodate Serving's need for internal/external then I'd frankly rather not unify the current `status.domain` field with `Addressable`.

My $0.02, happy to discuss more f2f this week.

**Comment by n3wscott** [comment]
UrlRef has a custom json mashaler that will send string and take string on the wire but as an object it is a parsed object. @mattmoor

**Comment by mattmoor** [comment]
Cool, as long as it's a string at rest, that SGTM.  Bear in mind that custom marshalers wreak havok on crd-gen :(

**Comment by mattmoor** [comment]
@akashrv and I spent some time talking about this, and I think the baseline thing that we want for `Addressable` is a single `url:` field.

```go
type Addressable struct {
         URL apis.URLRef `json:"url,omitempty"`
}
```

Ultimately, the `Addressable` contract is an agreement amongst producers and consumers.  Producers need to know what to publish, and consumers need to understand how to consume what's there.  In our case, URL is the lowest common denominator for this.

---

There are a variety of potential **extension** use cases that can complement this baseline.  One great example that comes up is: "multiple endpoints".  e.g. suppose instead of a simple function with request/response, I am hosting an API that has a different request/response on a variety of URL paths.  For this case I think having a `TypedAddressable` that is `Addressable` + schema would be extremely useful, and is a significantly richer way to surface this information than an ad hoc enumeration of supported endpoints.

```go
// Example not in scope for this proposal.
type TypedAddressable struct {
         Addressable `json:",inline"`

         Schema something.Schema `json:"schema,omitempty"`
}
```

Consumers of Addressable may choose to be sensitive to this additional metadata, should it be there, but they shouldn't require it because it may not always be there (graceful degradation).

**Comment by akashrv** [comment]
> multiple
Sounds good to me.

@evankanderson @vaikas-google @csantanapr @Harwayne @duglin 
Last time when I added you folks, my Github account was flagged and no notification was sent to anyone. Hence adding again. I remember you had particular use cases to extend addressable. Please share your thoughts here so that we can finalize and get this change in beta apis in 0.6 release (less than 2 weeks from now)

**Comment by akashrv** [comment]
> @akashrv and I spent some time talking about this, and I think the baseline thing that we want for `Addressable` is a single `url:` field.
> 
> ```go
> type Addressable struct {
>          URL apis.URLRef `json:"url,omitempty"`
> }
> ```
> 
> Ultimately, the `Addressable` contract is an agreement amongst producers and consumers. Producers need to know what to publish, and consumers need to understand how to consume what's there. In our case, URL is the lowest common denominator for this.
> 
> There are a variety of potential **extension** use cases that can complement this baseline. One great example that comes up is: "multiple endpoints". e.g. suppose instead of a simple function with request/response, I am hosting an API that has a different request/response on a variety of URL paths. For this case I think having a `TypedAddressable` that is `Addressable` + schema would be extremely useful, and is a significantly richer way to surface this information than an ad hoc enumeration of supported endpoints.
> 
> ```go
> // Example not in scope for this proposal.
> type TypedAddressable struct {
>          Addressable `json:",inline"`
> 
>          Schema something.Schema `json:"schema,omitempty"`
> }
> ```
> 
> Consumers of Addressable may choose to be sensitive to this additional metadata, should it be there, but they shouldn't require it because it may not always be there (graceful degradation).

Sounds good to me.

@evankanderson @vaikas-google @csantanapr @Harwayne @duglin 
Last time when I added you folks, my Github account was flagged and no notification was sent to anyone. Hence adding again. I remember you had particular use cases to extend addressable. Please share your thoughts here so that we can finalize and get this change in beta apis in 0.6 release (less than 2 weeks from now)

**Comment by vaikas-google** [comment]
URL is fine with me. I'm not conviced that Schema belongs at this level, who would fill it in? Currently the reconciler resolves the object into the endpoint, and ultimately the container providing the endpoint would have to surface some way (openapi endpoint, or ??) to surface this information and I don't immediately see a good way to handle this. Another issue that I've been thinking about is if authentication information needs to be here as well. I'm leaning towards making it an URLRef for now and extend it later once we have little more clarify on what else is necessary here in practice.
