### ISSUE TITLE
TestInterlevedExporters in metrics/exporter_test.go fails intermittently

### ISSUE THREAD

**Issue by akashrv** [knative/pkg#406]
## Steps to Reproduce the Problem

1. go clean -testcache & go test ./...
Try multiple times, the test fails intermittently with below error:
--- FAIL: TestInterlevedExporters (1.20s)
    logger.go:130: 2019-05-08T10:55:31.647-0700	INFO	TestInterlevedExporters	metrics/stackdriver_exporter.go:72	Created Opencensus Stackdriver exporter with config &{knative.dev/serving testComponent stackdriver 0 0 test-project false false  }
    prometheus_exporter_test.go:75: expected no server for stackdriver exporter
    logger.go:130: 2019-05-08T10:55:32.647-0700	INFO	TestInterlevedExporters	metrics/prometheus_exporter.go:38	Created Opencensus Prometheus exporter with config: &{knative.dev/serving testComponent prometheus 0 9090  false false  }. Start the server for Prometheus exporter.
    logger.go:130: 2019-05-08T10:55:32.847-0700	INFO	TestInterlevedExporters	metrics/stackdriver_exporter.go:72	Created Opencensus Stackdriver exporter with config &{knative.dev/serving testComponent stackdriver 0 0 test-project false false  }
--- FAIL: TestInterlevedExporters (1.20s)
    logger.go:130: 2019-05-08T10:55:31.647-0700	INFO	TestInterlevedExporters	metrics/stackdriver_exporter.go:72	Created Opencensus Stackdriver exporter with config &{knative.dev/serving testComponent stackdriver 0 0 test-project false false  }
    prometheus_exporter_test.go:75: expected no server for stackdriver exporter
    logger.go:130: 2019-05-08T10:55:32.647-0700	INFO	TestInterlevedExporters	metrics/prometheus_exporter.go:38	Created Opencensus Prometheus exporter with config: &{knative.dev/serving testComponent prometheus 0 9090  false false  }. Start the server for Prometheus exporter.
    logger.go:130: 2019-05-08T10:55:32.847-0700	INFO	TestInterlevedExporters	metrics/stackdriver_exporter.go:72	Created Opencensus Stackdriver exporter with config &{knative.dev/serving testComponent stackdriver 0 0 test-project false false  }
--- FAIL: TestInterlevedExporters (1.20s)
    logger.go:130: 2019-05-08T10:55:31.647-0700	INFO	TestInterlevedExporters	metrics/stackdriver_exporter.go:72	Created Opencensus Stackdriver exporter with config &{knative.dev/serving testComponent stackdriver 0 0 test-project false false  }
    prometheus_exporter_test.go:75: expected no server for stackdriver exporter
    logger.go:130: 2019-05-08T10:55:32.647-0700	INFO	TestInterlevedExporters	metrics/prometheus_exporter.go:38	Created Opencensus Prometheus exporter with config: &{knative.dev/serving testComponent prometheus 0 9090  false false  }. Start the server for Prometheus exporter.
    logger.go:130: 2019-05-08T10:55:32.847-0700	INFO	TestInterlevedExporters	metrics/stackdriver_exporter.go:72	Created Opencensus Stackdriver exporter with config &{knative.dev/serving testComponent stackdriver 0 0 test-project false false  }
--- FAIL: TestInterlevedExporters (1.20s)
    logger.go:130: 2019-05-08T10:55:31.647-0700	INFO	TestInterlevedExporters	metrics/stackdriver_exporter.go:72	Created Opencensus Stackdriver exporter with config &{knative.dev/serving testComponent stackdriver 0 0 test-project false false  }
    prometheus_exporter_test.go:75: expected no server for stackdriver exporter
    logger.go:130: 2019-05-08T10:55:32.647-0700	INFO	TestInterlevedExporters	metrics/prometheus_exporter.go:38	Created Opencensus Prometheus exporter with config: &{knative.dev/serving testComponent prometheus 0 9090  false false  }. Start the server for Prometheus exporter.
    logger.go:130: 2019-05-08T10:55:32.847-0700	INFO	TestInterlevedExporters	metrics/stackdriver_exporter.go:72	Created Opencensus Stackdriver exporter with config &{knative.dev/serving testComponent stackdriver 0 0 test-project false false  }

## Additional Info
Disbaled the test for now. Please enable it once this issue the resolved

**Comment by mattmoor** [comment]
cc @mdemirhan @yanweiguo

**Comment by yanweiguo** [comment]
Could reproduce it with a really low rate.

**Comment by vagababov** [comment]
/assign @jjzeng-seattle @evankanderson 
Is this still an issue or we can just close it out?

**Comment by jjzeng-seattle** [comment]
Yes we should close it.   The plan is to move to only `opencensus` exporter by the end of the year.  There won't be any interleaved exporters.
