### ISSUE TITLE
We should expose a way to do a GlobalResync scoped to a namespace.

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#409]
The idea is that when we have a shared resource that many things within a namespace rely on (e.g. default service account in K8s), that instead of using the tracker for such a dense space we would just have a way to resync all the objects in a particular namespace.

I suspect that this will be useful for wildcard certificates in Serving, and channels in Eventing.

cc @n3wscott  @vaikas-google @ZhiminXiang

**Comment by vagababov** [comment]
It won't be a global resync though :-)
It'll be a namespace resync.

**Comment by vagababov** [comment]
I think this possible to do with a simple filter?
