### ISSUE TITLE
TableTest - Delete in any order

### ISSUE THREAD

**Issue by Harwayne** [knative/pkg#411]
## Expected Behavior

We set the Table Test `WantDeletes` field as a slice. Normally we don't care about the order in which the deletes occur. We should either make the delete comparison unordered, or at least provide an option to make it unordered.

## Steps to Reproduce the Problem

1. Check out knative/eventing at 0a97ffcd0a93861a4e8fa2a7be82356530d1fd02
2. Run `go test ./pkg/reconciler/apiserversource -count 100`

## Additional Info

The client used by the unit tests returns lists in a non-fixed order, causing the unit test to flake when deleting everything in the list, as described in https://github.com/knative/eventing/pull/1230#issuecomment-491963450.

**Comment by vagababov** [comment]
/lifecycle frozen
/good-first-issue
This is super annoying
