### ISSUE TITLE
Risk condition: Failed calling admission webhook "webhook.eventing.knative.dev"

### ISSUE THREAD

**Issue by zxDiscovery** [knative/pkg#417]
## Expected Behavior

Deploy the knative eventing normolly.

## Actual Behavior

Deloy the knative eventing failed, error as follows:
Error: release knative failed: Internal error occurred: failed calling admission webhook "webhook.eventing.knative.dev": Post https://webhook.knative-eventing.svc:443/?timeout=30s: dial tcp 10.0.25.12:443: connect: connection refused

## Steps to Reproduce the Problem

This issue is led by https://github.com/knative/pkg/blob/5e4512dcb2cafff2779e6b1ba5091c642b4df2e1/webhook/webhook.go#L290
`RegistrationDelay` can't make sure the webhook create order correctly. 

We need the [server](https://github.com/knative/pkg/blob/5e4512dcb2cafff2779e6b1ba5091c642b4df2e1/webhook/webhook.go#L303) creates ready before the [`mutatingwebhookconfiguration`](https://github.com/knative/pkg/blob/5e4512dcb2cafff2779e6b1ba5091c642b4df2e1/webhook/webhook.go#L380) create

## Additional Info

https://github.com/knative/eventing/blob/master/config/500-webhook.yaml
https://github.com/knative/eventing/blob/master/config/400-webhook-service.yaml

**Comment by evankanderson** [comment]
Will this fix need to be backported to 0.6.0?

Do we know when it was introduced?

**Comment by vagababov** [comment]
> Will this fix need to be backported to 0.6.0?
> 
> Do we know when it was introduced?

My guess it has been there _forever_.
