### ISSUE TITLE
Versioning knative/pkg

### ISSUE THREAD

**Issue by dprotaso** [knative/pkg#430]
I'm curious if we've thought about ways to version this repository and whether it's a concern at this time. Currently we're not backwards compatible when changing our API surface area ie. https://github.com/knative/pkg/pull/427

**Comment by jchesterpivotal** [comment]
Agreed, this is a source of pain when consuming Knative from downstream.

**Comment by mattmoor** [comment]
Would it be helpful to simply snap release branches at the same time as the main repos (maybe the day before)?

**Comment by vdemeester** [comment]
@mattmoor that would definitely work for us (at least me :angel:)

**Comment by jchesterpivotal** [comment]
Yes, the same tag would be helpful, assuming they've been tested together.

**Comment by dprotaso** [comment]
> release branches at the same time as the main repos

What would the versions be?

**Comment by ryanbrainard** [comment]
This would be very helpful, The lack of versions broke our build in the v0.7.0 release of knative/serving because it referenced `apis.IsInStatusUpdate` in this repo, but there were no versions to reference, so I ended up having to use the most recent commit hash.

**Comment by mattmoor** [comment]
@ryanbrainard we have a `release-0.7` branch on knative/pkg now.
