### ISSUE TITLE
Use a flagset to define e2e flags

### ISSUE THREAD

**Issue by srinivashegde86** [knative/pkg#440]
/area test-and-release
/kind cleanup
/kind good-first-issue

Flagset is used to define a set of related flags. We can use a flagset to define the different set of flags used in our e2e tests.

More info on flagset:
https://golang.org/pkg/flag/#FlagSet

Example usage:
http://blog.ralch.com/tutorial/golang-subcommands/

**Comment by coryrc** [comment]
Given `go test`/testing now calls flag.Parse() for us, we don't really control flag parsing. So this is no longer relevant.

/close
