### ISSUE TITLE
Design / Implement webhook shared main

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#450]
Designed a "sharedmain" method for our webhooks to cut down on boilerplate.

**Comment by mattmoor** [comment]
Ideally this would also enable us to separate certificate provisioning from the actual webhook serving.

**Comment by vincent-pli** [comment]
@mattmoor 
Is this issue resolved, about `webhook`, `injection controller`?

**Comment by mattmoor** [comment]
Nope, we still need a way to share significantly more of what's in `./cmd/webhook/main.go` in each of the repos.

**Comment by vincent-pli** [comment]
Thanks, expect to see the design or discussion
