### ISSUE TITLE
Guide to generate informers

### ISSUE THREAD

**Issue by StrongMonkey** [knative/pkg#460]
I would like to generate a new informer(pod) for my pr to knative/serving but have no clue on the guide to generate those. Would be appreciated for any help regarding to this guide!

**Comment by evankanderson** [comment]
I'm not sure what you're looking for; would the generated client in serving work for you:

https://github.com/knative/serving/blob/master/pkg/client/informers/externalversions/serving/v1alpha1/service.go

**Comment by mattmoor** [comment]
The stuff under `./pkg/injection/informers/` is mostly hand-rolled copy/pasta while we work on generating the injection logic for out-of-tree types.  For in-tree types we have [a guide](https://github.com/knative/pkg/tree/master/injection#generating-injection-stubs).

That said, we have one for pods already here: https://github.com/knative/pkg/tree/master/injection/informers/kubeinformers/corev1/pod

**Comment by StrongMonkey** [comment]
Thanks for the follow-up. I found that pod informer is already generated.
