### ISSUE TITLE
Incomplete coverage for this repo

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#47]
The coverage dashboard for this repo only shows `pkg/apis` and `pkg/configmap`, but no other subdirectories.

https://testgrid.knative.dev/knative-pkg#coverage

**Comment by steuhs** [comment]
@mattmoor pkg/configmapdoes not have sub-packages. pkg/apis does have a subpackage but the subpackage contains no _test.go file.

**Comment by adrcunha** [comment]
knative/test-infra#110 should fix this issue, linking it here and bumping its dusty thread.

**Comment by steuhs** [comment]
Fixed
/close
