### ISSUE TITLE
Is there a plan to support kubernetes-1.13.x as dependency

### ISSUE THREAD

**Issue by houshengbo** [knative/pkg#513]
## Expected Behavior
We should support kubernetes-1.13.x, by changing Gopkg.toml.
```
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.5"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.5"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.5"

[[constraint]]
  name = "k8s.io/code-generator"
version = "kubernetes-1.13.5"
```
## Actual Behavior
Source code fails to build, after the dependency is updated.

## Steps to Reproduce the Problem

1. Change the Gopkg.toml, by replacing 1.12.9 with 1.13.5.
2. Update the dependencies.
3. Build the source code.

Related issues are: https://github.com/knative/client/issues/23, https://github.com/kubernetes/cluster-registry/issues/271, etc.

**Comment by jonjohnsonjr** [comment]
I think we have to decide we don't care about 1.11 anymore per the [version skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/). I'm not sure when that's true or what would break :)

**Comment by markusthoemmes** [comment]
We're on 1.15.x now.

/close
