### ISSUE TITLE
malformed  tracing ConfigMap causes pod `CrashLoopBackOff`

### ISSUE THREAD

**Issue by daisy-ycguo** [knative/pkg#514]
/area monitoring
/kind bug
/kind good-first-issue

## Expected Behavior

If user uses a malformed ConfigMap `config-tracing`, e.g. setting `enable` to `true` without `zipkin-endpoint` configured, or `sample-rate` is not a valid float, `activator` should disable tracing and continue or use a default value. Tracing is an observability feature and its misconfiguration shouldn't cause any pods to stop working. 

Refer to https://github.com/knative/serving/issues/4610 and https://github.com/knative/eventing/issues/1417.

## Actual Behavior

When a bad ConfigMap `config-tracing` is configured, following pods will become `CrashLoopBackOff` and keep on restarting:
- Serving activator
- Eventing broker filter
- Eventing broker ingress
- Eventing in-memory channel dispatcher
- Eventing gcppubsub channel dispatcher
- Eventing kafka channel dispatcher
- Eventing natss channel dispatcher

**Comment by vagababov** [comment]
We have validation in WH now, so this should not really be an issue.
