### ISSUE TITLE
WaitForEndpointState() in test package doesn't work for URL

### ISSUE THREAD

**Issue by ajanthan** [knative/pkg#557]
/kind bug
## Expected Behavior
It should work for both domain(without scheme) and URL

## Actual Behavior
When the URL is passed it is not working

## Steps to Reproduce the Problem

In any of the e2e test pass the URL  instead of Host it will fail

## Additional Info
This should be fixed to solve [#5030](https://github.com/knative/serving/issues/5030)

**Comment by vagababov** [comment]
There's also a flag which permits you to use the URL in the tests.

**Comment by ajanthan** [comment]
I hope you are referring to the theURL argument of [WaitForEndpointState](https://github.com/knative/pkg/blob/8a10634b4fa4df6dc450bfd883e85a33e76f2471/test/request.go#L137). If I pass a URL, it always fails because there is a bug in URL construction. For expample, if I pass http://example.com as an argument it constructs the URL as http://http://example.com (Parse method doesn't throw an error in this case)which causes the test to always fail.

**Comment by vagababov** [comment]
That's actually strange since this is a definitely malformed url.

**Comment by coryrc** [comment]
Given we pretty much only use URL now, can this be closed?

**Comment by vagababov** [comment]
/close
due to lack of activity
