### ISSUE TITLE
Calling `flag.Parse()` from shared lib prevents additional flags from being defined

### ISSUE THREAD

**Issue by jcrossley3** [knative/pkg#60]
Prior to [knative/serving#1937](https://github.com/knative/serving/pull/1937) there were more options available for running tests. Specifically, those in the `ServingEnvironmentFlags` struct, but because the flags are now parsed in `pkg/test`, none of the flags defined in `serving/test` are available now.

I'm thinking `serving/test` is where `flag.Parse` should be called.

**Comment by srinivashegde86** [comment]
All the common flags are now defines in pkg/test and can be called as pkgTest.Flags<Name> like https://github.com/knative/serving/blob/bfb3f5181b5ff18e4a16e9c158e8b9102404399c/test/e2e/e2e.go#L25

All the serving flags can be called with test.ServingFlags.<Name> like https://github.com/knative/serving/blob/bfb3f5181b5ff18e4a16e9c158e8b9102404399c/test/e2e/service_to_service_test.go#L124

**Comment by srinivashegde86** [comment]
https://github.com/knative/serving/pull/1937 removed the duplicated definitions and updated files in knative/serving to use the ones defined in knative/pkg

**Comment by srinivashegde86** [comment]
Created https://github.com/knative/pkg/issues/64 for this issue. Closing this.

**Comment by coryrc** [comment]
Flag parsing is now done by the testing library. So this bug is no longer relevant.
/close
