### ISSUE TITLE
Remove serving/eventing StackDriver specific metrics

### ISSUE THREAD

**Issue by nachocano** [knative/pkg#608]
## Expected Behavior
Currently, StackDriver is coupled with serving KnativeRevision metrics. Those metrics should be moved up to serving. Furthermore, eventing specific stuff should be moved to the appropriate eventing repo as well.

## Actual Behavior
There shouldn't be any serving nor eventing specific metrics in pkg.

## Additional Info
See for example https://github.com/knative/pkg/blob/e659f7b29204075fd33669ac4f1abd772a010f78/metrics/stackdriver_exporter.go#L87

/kind cleanup

**Comment by dprotaso** [comment]
related: https://github.com/knative/serving/pull/11659

**Comment by dprotaso** [comment]
related: https://github.com/knative/eventing/pull/5586
