### ISSUE TITLE
Error creating zipkin endpoint and missing traces

### ISSUE THREAD

**Issue by beemarie** [knative/pkg#613]
## Expected Behavior
No error messages in activator when zipkin endpoint is created as a result of configuration update.

## Actual Behavior
When tracing is enabled, the activator has the following error message:
{"level":"error","ts":"2019-08-28T13:40:11.650Z","logger":"activator-service","caller":"tracing/opencensus.go:133","msg":"error building zipkin endpoint","

Additionally, a number of traces are missing in zipkin - likely as a result of this failure.

## Steps to Reproduce the Problem

1. Enable tracing with zipkin backend
2. Check activator logs to see error message
3. Check zipkin to confirm missing traces

**Comment by jcchavezs** [comment]
Is this issue resolved @beemarie?

**Comment by beemarie** [comment]
Yep - I used "fixes" as the autoclose keyword, but it doesn't look like it was functional.  We can close this one.
