### ISSUE TITLE
We need a way to let repos define flags

### ISSUE THREAD

**Issue by srinivashegde86** [knative/pkg#64]
/area test-and-release
/kind cleanup

We should have flag parsing being performed in pkg, because that initializes the common logging infrastructure, and also avoids replicated boilerplate code (plus bug fixes, unification, etc). 

We should have a simple and documented process of adding extra flags defined in a repo/test/etc.

**Comment by coryrc** [comment]
This is fixed because `go test` does flag parsing now, and files like knative/serving/test/e2e_flags.go do define flags.
/close
