### ISSUE TITLE
Stop caching test loggers

### ISSUE THREAD

**Issue by vagababov** [knative/pkg#643]
Currently `TestLogger(t)` caches the loggers and then we need to call `ClearAll` to get rid of them.
There is not reason why we should cache the TestLogger in the library and then clean it up, rather than instantiate the logger in the test and give it to anything that needs that logger.

While this might bring some additional  work in the integration tests, unit tests should  mostly remain the same.
And some tests forget to clear test loggers and this causes panics when `count=2`.
 
## In what area(s)?

/area test-and-release
/kind good-first-issue

**Comment by mattmoor** [comment]
This is mostly relevant to unit testing which sets up controllers expecting a zap logger.  The integration tests have all moved to `t.Logf`

**Comment by taragu** [comment]
@vagababov the 3 PRs to remove test logger caching is ready for another review. Would you please take a look?

**Comment by mattmoor** [comment]
Is this done?

**Comment by taragu** [comment]
@mattmoor yep, this is done

**Comment by coryrc** [comment]
Based on the previous comment:
/close
