### ISSUE TITLE
Mako stub should output TSV for gnuplot

### ISSUE THREAD

**Issue by grantr** [knative/pkg#698]
According to @jchesterpivotal, gnuplot works best with TSV, but the Mako stub sidecar emits CSV only.

We can add a flag allowing this.

@nicholss

**Comment by slinkydeveloper** [comment]
Not sure there's a big difference between tsv and csv for gnuplot, it's just a matter of an additional command. Anyway I agree that we should have some "format" flag support to customize the output

**Comment by jchesterpivotal** [comment]
There isn't a difference on paper, but I just found that TSV behaved better in practice. CSVs tended to glitch more often.

**Comment by slinkydeveloper** [comment]
no problem for me, just let's keep both options. I'm using a custom tool that starting from mako output does some maths, so for me it's kinda important to keep csv, since my tool ingests csv https://github.com/slinkydeveloper/eventing-bench-results/blob/master/parse_run.sh

**Comment by grantr** [comment]
/close

If we determine we need tsv, we can reopen.
