### ISSUE TITLE
Capture pod resources as tags in mako.Setup

### ISSUE THREAD

**Issue by grantr** [knative/pkg#702]
I expect resource usage to change over the life of the benchmark. It would be nice to have Mako tags to record these things. Especially nice if mako.Setup captured them automatically :) Can we get pod resource requests and limits from the downward api?

/area test-and-release
/kind feature

**Comment by mattmoor** [comment]
@grantr maybe read it out of cgroups or use something like `runtime.ReadMemStat`?  This seems vaguely similar to what I was doing yesterday to project some of this information into opencensus metrics.

Also to clarify, you want this for the system-under-test, or the benchmark driver itself?  (the downward API comment is confusing me a bit)

**Comment by grantr** [comment]
I'm talking about the benchmark driver itself here, but system stats would be useful too. Reading out of cgroups would work if the pod has access to that.
