### ISSUE TITLE
Resolve compatibility with latest opencensus stackdriver exporter

### ISSUE THREAD

**Issue by garron** [knative/pkg#744]
## Actual Behavior

Using recent releases (newer than 0.12.5) of "contrib.go.opencensus.io/exporter/stackdriver" results in a failure to build knaitve.dev/pkg due to stackdriver.Options.GetMonitoredResource having been removed.

## Additional Info

I submitted https://github.com/knative/pkg/pull/730 to add a constraint in order to prevent build failures, but work should still be done to reach compatibility with recent releases of that package. This issue is intended to track that work.

Commit which removed the option:
https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/commit/b0cbe77587ebe726c8dc9d4d00101c28c7ac2527

**Comment by yanweiguo** [comment]
Created https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/230

**Comment by yanweiguo** [comment]
Found another issue: https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/237
