### ISSUE TITLE
Change Destination API and modify addressable resolver based on the new Destination API

### ISSUE THREAD

**Issue by capri-xiyue** [knative/pkg#772]
## Expected Behavior
In https://github.com/knative/eventing/issues/1918, people have a discussion regarding the Destination API. The conclusion for that discussion is as follows:
```go
type Destination struct{
  // +optional
  Ref *corev1.ObjectReference
  // +optional
  URI *apis.URL
}
```
Validation rules for Destination:
- If Ref is absent and URI is absent, the Destination is invalid.
- If Ref is present and URI is absolute (`URL.IsAbs()` returns true), the Destination is invalid.
- If Ref is absent and URI is relative (`URL.IsAbs()` returns false), the Destination is invalid.
- All other Destinations are valid.

Also need to modify the addressable resolver as follows:
Target URI resolution rules:

If URI field is absent, the target URI is the URI retrieved from Ref.
If URI field is present and absolute, the target URI is the value of the URI field.
If URI field is present and relative, the target URI is the result of calling URL.ResolveReference with the URI retrieved from Ref as the base URI and the value of the URI field as the URI reference.

**Comment by aslom** [comment]
@capri-xiyue after Destinations are valid I would add how actually Ref and URI are resolved to create new URI?

* if Ref is present then 
    * if there's no URI then resolve Ref and use that as URI
    * else if URI a relative then resolve Ref with relative URI and use resolved URI
    * else Error: URI can not be absolute if Ref is present 
* else If there's no Ref then 
    * if URI is absolute then use it
   * else Error: URI is not absolute
* else Error: at lease URI or Ref must be present

**Comment by capri-xiyue** [comment]
@aslom  I already finished the resolve part in this PR https://github.com/knative/pkg/pull/774
