### ISSUE TITLE
Mako stub log doesn't report all columns

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/pkg#799]
/area test-and-release
/kind feature
/kind good-first-issue

## Expected Behavior
Mako stub should print all columns always in same order (that could be the defined order in the .config file), including the one without data points.

This simplifies the scripting for result processing

## Actual Behavior
Mako stub doesn't print all columns. e.g. when no error occurs, no failure column appears

**Comment by grantr** [comment]
:+1: This would be a useful improvement.

**Comment by slinkydeveloper** [comment]
@grantr there is any way from mako apis to retrieve all metrics described in `dev.config` file? Because I can't find it :)

**Comment by grantr** [comment]
Good idea! `dev.config` is a proto file in text format defined at https://github.com/google/mako/blob/master/spec/proto/mako.proto#L255. knative/pkg parses it to get the benckmark key: https://github.com/knative/pkg/blob/master/test/mako/config/benchmark.go#L54
