### ISSUE TITLE
Lots of imports when creating a condition

### ISSUE THREAD

**Issue by dprotaso** [knative/pkg#81]
For example creating a Condition for a route requires three package imports

- `duckv1alpha1` 
- `servingv1alpha1` 
- `corev1`

For example:
```go
duckv1alpha1.Condition{
	Type:    v1alpha1.RouteConditionAllTrafficAssigned,
	Status:  corev1.ConditionUnknown,
	Reason:  "RevisionMissing",
	Message: `Configuration "not-ready" is waiting for a Revision to become ready.`,
}
```

I'm curious if people would consider type aliasing and potentially some `go:generate` to automate the aliasing to produce something with one import

For example:
```go
v1alpha1.Condition{
	Type:    v1alpha1.RouteConditionAllTrafficAssigned,
	Status:  v1alpha1.ConditionUnknown,
	Reason:  "RevisionMissing",
	Message: `Configuration "not-ready" is waiting for a Revision to become ready.`,
}
```

**Comment by mattmoor** [comment]
IDK if we need codegen, I think it's going to literally be the same file in every case.  I think the only piece that varies is the stuff in `servingv1alpha1` (or equivalent).

I think @n3wscott had half of this initially and I'd recommended removing it, but I am coming around to the logic.

I'm a little concerned that the type aliasing will cause us to need casts for this to work, have you tried it?

**Comment by n3wscott** [comment]
> I think @n3wscott had half of this initially and I'd recommended removing it, but I am coming around to the logic.

I did! :D

Instead of this:

```
duckv1alpha1.Condition{
	Type:    v1alpha1.RouteConditionAllTrafficAssigned,
	Status:  corev1.ConditionUnknown,
	Reason:  "RevisionMissing",
	Message: `Configuration "not-ready" is waiting for a Revision to become ready.`,
}
```

How would this feel:

```
duckv1alpha1.NewCondition( v1alpha1.RouteConditionAllTrafficAssigned).MarkUnknown(
   "RevisionMissing",
   "Configuration %q is waiting for a Revision to become ready.",
    notReady)
```

And we do not alias the `corev1` status types, we just add the mark methods to the `Condition` type.

Further, we could move `NewCondition` to `duck` and have it default to a version for `Condition` (for now it will be `v1alpha1`)

i.e.

Unknown: 

```
duck.NewCondition( v1alpha1.RouteConditionAllTrafficAssigned).MarkUnknown(
   "RevisionMissing",
   "Configuration %q is waiting for a Revision to become ready.",
    notReady)
```

Ready: 

```
duck.NewCondition( v1alpha1.RouteConditionAllTrafficAssigned).MarkReady()
```

**Comment by n3wscott** [comment]
@dprotaso @mattmoor ^^^

**Comment by mattmoor** [comment]
If y'all still want this, we should do something about it.  Otherwise `/close`?

**Comment by dprotaso** [comment]
Wow forgot about this
