### ISSUE TITLE
Istio LDS becoming stale due to invalid privateKey

### ISSUE THREAD

**Issue by xUnholy** [knative/pkg#831]
https://github.com/knative/pkg/blob/3732de5802012193835c9fe65436b761ed3fecea/apis/istio/v1alpha3/gateway_types.go#L255

This value should be omitted if empty and be a pointer.

If CredentialName is being used this field is not required - it will also make the Istio LDS become stale with an error saying the PrivateKey cannot be found, of course this is because privateKey is an empty string and cannot be removed.

`istio-ingressgateway-6d989f4cfb-wxpkd istio-proxy [2019-10-29 06:27:23.147][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:77] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: Failed to load private key from <inline>`

**Comment by xUnholy** [comment]
I'm using this package because the official Istio package `istio.io/api/networking/v1alpha3` doesn't support deep copy object, which I require as I'm creating a Kubernetes operator.

I've noticed this package has drifted from the before mentioned package, I'm not sure if that is intended however, it would be great if we can regain parity with the upstream changes.

**Comment by xUnholy** [comment]
The following PR is currently open with an attempt to update the Istio Gateway Spec however it is also now outdated and invalid. 

https://github.com/knative/pkg/pull/736

There needs to be a better way of going forward to keep parity.

Here is the upstream Istio Gateway Spec for TLSOptions that we should be trying to gain parity with.
https://godoc.org/istio.io/api/networking/v1alpha3#Server_TLSOptions

**Comment by tcnghia** [comment]
/close

This is obsolete, we moved to istio/client-go.
