### ISSUE TITLE
Split apart resource webhook

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#847]
_For a bit [more context](https://twitter.com/mattomata/status/1191015959269531648)_

[Background](https://kubernetes.io/blog/2019/03/21/a-guide-to-kubernetes-admission-controllers/).

Mutating webhooks are executed serially to generate patches of mutations to apply to resources prior to validation, which (it seems?) execute in parallel, before committing the resource to etcd.

Currently we perform defaulting and validation in the same webhook, see this comment in the article:
> However, even a mutating admission webhook can reject requests and thus act in a validating fashion.

However, **doing any meaningful validation in a mutating webhook is an anti-pattern.**

The reason for this is that if multiple mutating webhooks are registered, then the later webhooks could arbitrarily violate validations performed by earlier webhooks.

With our newly refactored webhook, it should be relatively trivial for us to split these apart and run them as two reconcilers that implement `webhook.AdmissionController` for these separate pieces of logic.

/assign

**Comment by jchesterpivotal** [comment]
I have two questions.

1. By "which (it seems?) execute in parallel", do you mean the patches supplied by mutating webhooks are applied in parallel, or at least in an undefined order?
2. By "split", do we mean controllers running in distinct pods?

**Comment by mattmoor** [comment]
@jchesterpivotal look at the diagram in the background article, I think it says it better than my words.  I do not mean separate pods, but more like `/defaultable` and `/validatable` on the same pod.
