### ISSUE TITLE
Introduce interfaces for metrics exporter

### ISSUE THREAD

**Issue by yanweiguo** [knative/pkg#866]
In metrics exporter code, we have some `if` statements to do different behaviors if the backend is Stackdriver or Prometheus. Some global variables are used for a specific backend only. For example the Prometheus service. These are not good.

We can introduce interfaces like
```
type metricsExporter interface {
 Start()
 Stop()
 Flush()
}
```

**Comment by grantr** [comment]
@yanweiguo do you think this would be a good first issue?

**Comment by yanweiguo** [comment]
Given we're migrating to OpenCensus collector, we can close this.
