### ISSUE TITLE
Separate test/prow library with another package with functions with lite dependencies

### ISSUE THREAD

**Issue by yt3liu** [knative/pkg#873]
## Expected Behavior

Functions in test/prow that does not depending on non-builtin functions are separated out as a separate package so for files that do not use those heavy functions, they do not need to pull in heavy dependencies. 

## Actual Behavior

When a file only needs `GetLocalArtifactsDir` requires adding "cloud.google.com/go/storage" and "google.golang.org/api/option" as dependencies.

**Comment by vagababov** [comment]
/assign @chizhg @chaodaiG 
Do we still need this?

**Comment by chaodaiG** [comment]
This is obsolete.
/close
