### ISSUE TITLE
Unite underlying log libraries into Zap

### ISSUE THREAD

**Issue by coryrc** [knative/pkg#883]
Our project has chosen to use Zap for structured logging. Some of our dependencies (Mako, client-go) use other logging libraries: glog, klog. Those two don't coexist well and we shouldn't have several knobs to control logging.

Istio team had this same issue and has a very neat solution of writing API wrapper with calls to Zap, and updating go.mod to redirect imports for github.com/golang/glog and k8s.io/klog to the wrappers. We can do the same thing with Go dep and reuse Istio's wrappers.

Then all logging can be controlled with one package. This needs to be done in all repos.

Istio wrappers:
https://github.com/istio/klog/
https://github.com/istio/glog/

**Comment by coryrc** [comment]
Somewhat related: #441

**Comment by coryrc** [comment]
klog provides a way: https://github.com/kubernetes/klog/blob/8422fac62d1e961e89426ffb5ae3a07f2d0bcca2/klog.go#L775

+ the glog->klog wrapper should do the job

**Comment by grantr** [comment]
@coryrc do you think this would be a good first issue?

**Comment by coryrc** [comment]
No.

I've sent PRs to the mentioned repos. Maybe we need to fork them or I need to directly contact people to get the changes through.

**Comment by grantr** [comment]
Ok, thanks for explaining. I didn't realize this was about getting repos owned by other organizations to change their logging libraries. That doesn't seem like a good first issue at all.

**Comment by coryrc** [comment]
knative/serving#6976 could be completed if the repos at [glog](https://github.com/coryrc/glog) and [klog](https://github.com/coryrc/klog) were brought into knative-sandbox.
/unassign
