### ISSUE TITLE
Compile error using 1.14.6 k8s libs

### ISSUE THREAD

**Issue by jcrossley3** [knative/pkg#895]
This [line](https://github.com/knative/pkg/blob/2ec0f8da50578dcc3d830571d0de24de834579c8/client/clientset/versioned/typed/istio/v1alpha3/istio_client.go#L83) gives me the following error using 1.14.6 k8s libs:
```
vendor/knative.dev/pkg/client/clientset/versioned/typed/istio/v1alpha3/istio_client.go:83:45: scheme.Codecs.WithoutConversion undefined (type serializer.CodecFactory has no field or method WithoutConversion)
```
The `authentication_client.go` has the same problem.

I tried using 1.15.3 libs but that introduced other problems going against a 1.14.6 cluster. If 1.14.x is the minimum supported k8s version, shouldn't the libs compile? It seems that `WithoutConversion` function was introduced in 1.15.

**Comment by markusthoemmes** [comment]
Compatibility with a 1.14 cluster shouldn‘t be determined by whether or not the respective Golang libs compile.

IIRC the clients should have +/- 1 version compatibility.

I‘m curious which issues have been causes by the clients on a 1.14 cluster, can you elaborate?

**Comment by vagababov** [comment]
/close

We're up to 1.16 now, I think.
