### ISSUE TITLE
Generate JUnit directly from tests (remove necessity of go-junit-reporter)

### ISSUE THREAD

**Issue by coryrc** [knative/pkg#901]
go-junit-reporter is not being supported (we have [open bugs](https://github.com/jstemmer/go-junit-report/issues/95), PRs are languishing) so lets generate the JUnit directly.

As part of improving logging this can fix #441 and [eventing#1894](https://github.com/knative/eventing/issues/1894), as well as offer a good way to make conformance tests print better output.

**Comment by chizhg** [comment]
I believe you investigated on [gotestsum](https://github.com/gotestyourself/gotestsum) a bit before, are you referring to this tool here in this issue?

**Comment by coryrc** [comment]
I was not, I am trying out what it looks like to generate it in the logging module. gotestsum would not help with eventing#1894 either.

**Comment by coryrc** [comment]
Err, maybe it would because the json output streams?

**Comment by coryrc** [comment]
Any tool that runs after can't collect all log messages for tests that are run in parallel (unless JSON stream annotates them perfectly, I will investigate)
But if we collect logs in real time to other file(s) it doesn't matter if JUnit doesn't have everything in it.

**Comment by coryrc** [comment]
For now, 907 addresses more issues and will re-open if this becomes necessary.
