### ISSUE TITLE
Verify that the K8s service actually exists in K8s in func URIFromObjectReference

### ISSUE THREAD

**Issue by capri-xiyue** [knative/pkg#923]
## Expected Behavior
We should be able to know whether K8s service actually exists in K8s in func URIFromObjectReference()
## Actual Behavior
Currently, we can still resolve URI from K8s service even though it doesn't exists.

**Comment by vagababov** [comment]
@capri-xiyue 
is this still a desired improvement?

**Comment by capri-xiyue** [comment]
> @capri-xiyue
> is this still a desired improvement?

Yep. This is still a desired improvement.

**Comment by vagababov** [comment]
Are you going to work on it?

**Comment by capri-xiyue** [comment]
> Are you going to work on it?

I may not have cycles in a short time. If someone else have free cycles,  please feel free to pick up this tasks. 
If not, I will revisit it when I have cycles.
