### ISSUE TITLE
client_test.go should not require gcloud application default credentials

### ISSUE THREAD

**Issue by coryrc** [knative/pkg#934]
Cloned knative/pkg.
Ran `go test ./...`
All tests pass except `pkg/test/gke/client_test.go`
Ran `gcloud auth application-default login`
Now all tests pass.

I don't believe unit tests should require 3rd-party software to be configured.
Or if they do, this should be documented in this repo somehow.

**Comment by coryrc** [comment]
cc @adrcunha as he appears to be creator of the file

**Comment by adrcunha** [comment]
This was created by @chaodaiG . Seems like a simple fix; we never had any issues with that because credentials are already setup in a Prow job.

**Comment by evankanderson** [comment]
From #957:

> I'm guessing this uses [`x.oauth2.google.FindDefaultCredentials`](https://godoc.org/golang.org/x/oauth2/google#FindDefaultCredentials), which says:
> 
> It looks for credentials in the following places, preferring the first location found:
> 
> 1. A JSON file whose path is specified by the
>    `GOOGLE_APPLICATION_CREDENTIALS` environment variable.
> 2. A JSON file in a location known to the gcloud command-line tool.
>    On Windows, this is `%APPDATA%/gcloud/application_default_credentials.json`.
>    On other systems, `$HOME/.config/gcloud/application_default_credentials.json`.
> 3. On Google App Engine standard first generation runtimes (<= Go 1.9) it uses
>    the `appengine.AccessToken` function.
> 4. On Google Compute Engine, Google App Engine standard second generation runtimes
>    (>= Go 1.11), and Google App Engine flexible environment, it fetches
>    credentials from the metadata server.
> 
> We should be able to set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to point to either an empty file, or a temp file with bogus credentials to make sure there are no GCP dependencies in our tests.

**Comment by chizhg** [comment]
/assign
I'll work on the fix.
