### ISSUE TITLE
Add export to OpenCensus Agent to `pkg/metrics`

### ISSUE THREAD

**Issue by evankanderson** [knative/pkg#955]
## Expected Behavior

Users should be able to use 'metrics.backend-destination = "ocagent"' in `config-observability` to export metrics to the [OpenCensus Agent](https://opencensus.io/exporters/supported-exporters/go/ocagent/) on the default host and port (`localhost:55678`).

Over time, this will become the default, and then the only option.

## Actual Behavior

Only Prometheus (default) and Stackdriver are supported.

**Comment by dprotaso** [comment]
Note: this was added here: https://github.com/knative/pkg/pull/978

```yaml
metrics.backend-destination: "opencensus"
```
