### ISSUE TITLE
Add reference of Subscription to ChannelSubscriberSpec

### ISSUE THREAD

**Issue by vaikas** [knative/pkg#96]
## Expected Behavior
When adding a ChannelSubscriberSpec it's not possible to currently have duplicate subscriptions and it is probably better to include either an ObjectRef or something like that as part of the entry being added to the list so that Subscription Controller can keep track of Subscription -> Entry in the list of subscribers.

// ChannelSubscriberSpec defines a single subscriber to a Channel.
// CallableDomain is the endpoint for the call
// SinkableDomain is the endpoint for the result
// One of them must be present
type ChannelSubscriberSpec struct {
	// +optional
	CallableDomain string `json:"callableDomain,omitempty"`
	// +optional
	SinkableDomain string `json:"sinkableDomain,omitempty"`
}

Right now for example it's not possible to have duplicate Subscriptions because of this. Well, at least not correctly without complicating things (like refcounting).

@grantr @n3wscott 

## Steps to Reproduce the Problem

  1.
  2.
  3.

**Comment by vaikas-google** [comment]
@evankanderson

**Comment by evankanderson** [comment]
Ah -- you're saying that it's impossible to set up two subscriptions from A calling C if you want to call C twice for some reason. (I'm not sure why you would do this, but it seems like two subscriptions should cause two messages to be delivered.)

Adding the subscription name (either as ObjectReference or namespace+name string(s)) to the ChannelSubscriberSpec would seem to fix this, and would make it somewhat easier to handle individual deltas. I think there may still be a tricky question on how to remove stale channels if we miss a Subscription delete edge.

**Comment by vaikas-google** [comment]
I'm going to play with this tomorrow. I think we wouldn't necessarily remove a subscription unless we remove channels (via finalizers?)
I think it might be better to use ObjectReference instead of namespace/name (which was actually my first thought) in case there's other objects later on that can create subscriptions. Thoughts?
