### ISSUE TITLE
RFE: func WaitForXXXX should print last state of the resource when failed

### ISSUE THREAD

**Issue by nak3** [knative/pkg#996]
/area test-and-release

When `func WaitForXXXX` in [test/kube_checks.go](https://github.com/knative/pkg/blob/master/test/kube_checks.go) failed, it just prints the error as `timed out waiting for the condition`.

(e.g.) [autoscale_test.go](https://github.com/knative/serving/blob/4505ff00396d4acd85cd079ce7f20d815927d157/test/e2e/autoscale_test.go#L230-L232)
```
    autoscale_test.go:231: Unable to observe the Deployment named autoscale-up-down-up-tvuqkpaq-bjqz2-deployment scaling down: timed out waiting for the condition
```

So, it is still difficult to know why it fails. It would be useful if we can get the last state of the resource.

Actually serving project implements it in `WaitForConfigurationState()` for their resources as:

https://github.com/knative/serving/blob/4505ff00396d4acd85cd079ce7f20d815927d157/test/v1beta1/configuration.go#L119-L137

so test/kube_checks.go could be changed as same manner.

**Comment by MIBc** [comment]
I'd like to try.

**Comment by nak3** [comment]
Sure. I would highly appreciate if could take it. But I'm still not sure if this idea will be accepted or not.

**Comment by vagababov** [comment]
/good-first-issue
/lifecycle frozen
I find this a useful improvement for test debuggability.

**Comment by skonto** [comment]
I can do it if no one else is interested.
